### ISSUE TITLE
Cannot import sikulixapi from jython if packages are installed in read only folder

### ISSUE THREAD

**Issue by offlinehacker** [RaiMan/SikuliX-2014#101]
First i would like to thank for your work on sikuli, i have been searching for other alternative solutions, there are none, i hope sikulix2 will be even better.

I have created sikuli package for nixos linux distribution(https://github.com/NixOS/nixpkgs/pull/6463) and now i want to import sikulixapi.jar which is stored in read only path from jython. This is error i get:

```
[error] ResourceLoader: checkLibsDir: Not a valid libs dir for SikuliX (amd64): /nix/store/29jz01l2van8p6qrr4spx3q2a76h0yvh-sikulix-1.1.0/libexec/sikulix/libs
[error] ResourceLoader: copyResource Not possible: /nix/store/29jz01l2van8p6qrr4spx3q2a76h0yvh-sikulix-1.1.0/libexec/sikulix/libs/1.1-MadeForSikuliX64L.txt (Permission denied)
[error] ResourceLoader: copyResource Not possible: /nix/store/29jz01l2van8p6qrr4spx3q2a76h0yvh-sikulix-1.1.0/libexec/sikulix/libs/libJXGrabKey.so (Permission denied)
[error] ResourceLoader: copyResource Not possible: /nix/store/29jz01l2van8p6qrr4spx3q2a76h0yvh-sikulix-1.1.0/libexec/sikulix/libs/libVisionProxy.so (Permission denied)
[error] ResourceLoader: checkLibsDir: Not a valid libs dir for SikuliX (amd64): /nix/store/29jz01l2van8p6qrr4spx3q2a76h0yvh-sikulix-1.1.0/libexec/sikulix/libs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/offlinehacker/nix/workdirs/master/result/libexec/sikulix/sikulixapi.jar/Lib/sikuli/__init__.py", line 6, in <module>
  File "/home/offlinehacker/nix/workdirs/master/result/libexec/sikulix/sikulixapi.jar/Lib/sikuli/Sikuli.py", line 30, in <module>
java.lang.ExceptionInInitializerError
```

So as i can see copyResource fails. But i wonder why does checkLibsDir fail at the first place. SikuliX ide runs just fine.

If i put sikuli in writable path it works just fine.

**Comment by offlinehacker** [comment]
So in our case fix was to build only with option 1.1 and then ide and jython bindings work, so i'm closing this one.

**Comment by RaiMan** [comment]
The above pointer to the nixes issue gave me the way to the github location.
But I could not find the Sikuli package at the place the pull request patches point to.

generally:
when you use the nightly stuff for an offline setup (what you seem to do in your packaging), then always all downloaded artefacts must belong to the same nightly build.
this affects
sikulixsetup
1.1.0-1
1.1.0-2
and in your case
libslinux

BTW: the final 1.1.0 (partly already in the next nightly) will not export anymore to the folder holding the active artefact (libs, Lib, tessdata), but to standard places in the user home directory (or other places by option).
And the lib exports will be tagged with the build timestamp.
So it is now possible to freely move/copy the artefacts (sikulix.jar, sikulixapi.jar) wherever you want.

**Comment by offlinehacker** [comment]
Currently the biggest issue we have, is that nightly builds are not tagged
with some unique identifier. This way package can't be really created,
because hashes of the package change all the time.

We would be the most happy with a new stable release.

**Comment by RaiMan** [comment]
Hope, that this is not a general misunderstanding:
-- 1: to get a running IDE, from the latest nightly build, you have to take the respective setup jar and download the respective jars needed (see above). the downloaded jars on it's own are not useable, but have to be run through setup (in your case the silent setup inside the package installation).

-- 2: to get a useable sikulixapi.jar, you might go the same path or get the snapshots from sikulixapi.jar and sikulixlibslinux from OSSRH (pre MavenCentral) (repo pointer see homepage)

... and on linux you currently still have the problem, that depending on the prerequisites the provided libVisionProxy.so might not work and has to be built from the sources on this system.

Currently (nightly mid January) the "build on the fly is only supported in setup, but not in the Maven artefact (this is what I am currently working on for one of the next nightlies/snapshots and the final 1.1.0).
This is why I want to know, how you currently tackle this challenge: libVisionProxy.so does not work.
