### ISSUE TITLE
Any plans for a new stable release?

### ISSUE THREAD

**Issue by offlinehacker** [RaiMan/SikuliX-2014#102]
There has been some time from latest stable release of sikulix. I can see that you have nightly builds, but i'm packaging siklix in nixos linux distribution and i want to get versioning right.

**Comment by RaiMan** [comment]
Mid of January I decided, to revise some vital areas (startup, script run support, linux "libVisionProxy-build-onthefly", ...). The nightlies are paused since then. The next nightly will be available during coming weekend. The final 1.1.0 will be available mid of March.

What parts of Sikuli are you packaging with nixos?
How did you solve the OpeneCV/Tesseract dependency challenge?
How did you solve the libVisionProxy.so build?

I would be interested in this dependency control and the libVisionProxy.so build you are using, to check it against my "build-on-the-fly" workflow.

**Comment by offlinehacker** [comment]
So in nixos we have nix package manager, that already has opencv and
tessarect. Because detection of library paths with ldconfig, is kinda wrong
and does not work in our use case, it could present a problem, but in our
use-case g++/GCC/CC and others are wrappers, where we were able to inject
library paths and it just worked.

What i would like(from a guy with huge experience with packaging software)
to see from setup, that it wouldn't be so smart. I would rather like to
have it better documented and being more manual and more standard, than
having some automation that you never know whether it would work or not. I
had to spend quite some time, figuring out how to tackle it.

I would sugguest:

- separating builds for native libraries and java.
- autotools or at least simple makefile for building native libraries
- usage of something like NATIVE_LIBS or similar environment variabes to
override bundled binaries in JAR file
- extraction of resources from JAR file to /tmp, where every process can
write.
- message which points to documentation, how to build if imports of bundled
native libraries fail
- Versioned nightly builds
- More often releases

I might be able to help you here. Because we are already building packages
for nixos linux distro on hydra.nixos.org, i could setup builds for sikuli
if you are interested.
Nix package manager builds packages in a deterministic fasion and it works
on all unix systems(linux, osx).

**Comment by offlinehacker** [comment]
And yes, we are reusing setup to create package, but we want to get rid of
this.

**Comment by RaiMan** [comment]
I fully agree with all your points and suggestions, but I have to admit, that supporting any repackaging is not my main focus.
On Mac and Windows, this challenge does not exist anyways and on Linux I think I am short before supporting the main distributions (Ubuntu, Debian, RedHat, CentOs and Fedora) from setup.
For the others I want to make life as easy for them as possible: spit out a build script, that has to be adapted to their situation and works.
I will not invest in any of these native support stuff like auto tools and make and whatever. If anyone comes up with a good solution for that: welcome.
Another reason to not invest here: I will cut off any native coding with version 2 anyways. Everything will be on the Java level, accessing the OpenCV, Tesseract and system specific things via available bridging/binding libraries. I have already started with this (switched off in the distribution) for OpenCV features.

what I will do:
- concentrate all the linux library stuff into sikulixlibslinux and make it runnable about the checking and building (additionally to the usage with setup)
- document the options to use, that hinder setup from doing anything with the native stuff (neither export nor build)
- make the nightly files versioned

apart from that I will not do any major changes in version 1.1.x

**Comment by RaiMan** [comment]
BTW: Of course I highly appreciate your input and will accept any contributions that are intended to make YOUR life easier.

**Comment by offlinehacker** [comment]
I can't wait for version 2. Appart from lack of versioned nightly builds,
we don't have problems in nixos anyway.

**Comment by RaiMan** [comment]
ok, fine.

then how would a versioning of the nightly artefacts be suitable for you?

something like the maven snapshot numbering with a timestamp?

or some number (e.g. year + number of day?)

I do not need it anyways, since I internally have my build timestamp.

**Comment by offlinehacker** [comment]
It does not really matter, we just need unique download URL, then, what you
prefer more. Also retention of old nightly releases is needed(for
reasonable amount of time), so our builder is able to download packages at
any time.

**Comment by RaiMan** [comment]
I already expected this kind of request, but I will definitely not retain more than one nightly set, which is the latest one.
The number I will add can thus only be used, to decide, wether it makes sense to download a newer version than that already built.

**Comment by offlinehacker** [comment]
Well in that case versioned nightly builds wouldn't really help us and we
will have to host binaries ourselves, or build from source. Would it help
you if nixos provides nightly builds for you using hydra build system(
hydra.nixos.org)

**Comment by RaiMan** [comment]
hydra.nixos.org: No problem, tell me what you need from my side.

**Comment by offlinehacker** [comment]
Also, what about static builds for visionProxy, this would make possible to
make it run on any linux distro?

**Comment by RaiMan** [comment]
static build: 
I already thought about that, but since I am not that expert in building native stuff, I left it aside.
Can you do that with your nixos packager?

**Comment by datakurre** [comment]
For what it is worth, I believe, I managed to build SikuliX on NixOS by using the current versioned releases, reusing the previous work by @offlinehacker. IDE starts, I can capture screenshots for scripts and execute scripts properly.

https://github.com/datakurre/nix-files/commit/652c4f9656d4ac340143c830b6e165dd7bc4d127
