### ISSUE TITLE
missing java source/javadoc package 

### ISSUE THREAD

**Issue by nschle85** [RaiMan/SikuliX-2014#105]
Developing using sikulix without source or javadoc package is very unhandy, please provide them. If generating them is blowing your infrastructure you should provide a build switch, otherwise please re-enable generating them.

**Comment by RaiMan** [comment]
Feel free to do what you want in your fork. Even if together with a pull request it will be switched on again, I can live with this inconvenience ;-)
It is not blowing my infrastructure, but it is my time during testing, that is wasted.
The Maven/OSSRH upload sikulixapi.jar is with docs and sources anyway and I think, this is what finally counts.
