### ISSUE TITLE
URL SetBundlePath Issue

### ISSUE THREAD

**Issue by wakeyowl** [RaiMan/SikuliX-2014#107]
Hi RaiMan,

On the updates you made for me to alow a URL Path we are encountering an issue setting either path now on windows machines.

We have 2 seprerate issues initially when we are rying to set the bundle path with url

ImagePath.setBundlePath("http://google.co.uk/");

returns the following:
[error] ImagePath: add: class /C:/Users/benk/workspace - new/whgtf-demo-test/http:/google.co.uk not found on classpath.
[error] ImagePath: setBundlePath: invalid BundlePath: http://google.co.uk/ 
using working folder: C:\Users\benk\workspace - new\whgtf-demo-test

I assume we are doing this correctly?

Also the updates seem to have broken the filepath of a system folder when it contains spaces and/or special chars. i.e. C:/Users/benk/workspace - new/whgtf-demo-test

ImagePath.setBundlePath(System.getProperty("user.dir"));

The above now returns (and loops quite a bit 471 times infact :-) : 
[error] ImagePath: setBundlePath: invalid BundlePath: C:\Users\benk\workspace - new\whgtf-demo-test 
using working folder: C:\Users\benk\workspace - new\whgtf-demo-test

Having debugged it, compairing to 1.1.0 version this is the code that causes the exception within ImagePath.java
		public String getPath() {
			if (pathURL == null) {
				return "-- empty --";
			}
			if (isFile())
				try {
					return pathURL.toURI().getPath();
				} catch (URISyntaxException ex) {}
			return pathURL.toExternalForm();
		}

as a workaround we changed the code to read "return pathURL.getPath()" as per the earlier version.

**Comment by RaiMan** [comment]
sorry, I have overseen this post.

I will check it. thanks.

**Comment by RaiMan** [comment]
only ImagePath.addHTTP() can be used to add a pointer to the net.

setBundlePath() can only be used with Filesystem path's, which is due to the fact, that the bundle path is also the pointer for the IDE to store captured images.
All this will only be revised in version 2, where the 1.1.x-bundle will be a subset of a project, that contains everything needed (code, images and options) - something like a Maven project with a pom-file.

I have fixed the problem with the above toURI()-usage, in a way, so it is consistent with the other implementations around path handling (so not simply going back to the artier version as you did ;-)

anyway: thanks for finding.

**Comment by wakeyowl** [comment]
Hi Rai,

I raise a ticket about the setBundle path some time ago regarding the
requirement to use an http image repository. (see History of the email
chain below)

In it you said:

"setBundlePath() can only be used with Filesystem path's, which is due to
the fact, that the bundle path is also the pointer for the IDE to store
captured images.
All this will only be revised in version 2, where the 1.1.x-bundle will be
a subset of a project, that contains everything needed (code, images and
options) - something like a Maven project with a pom-file."

This was back in February could you give me an update on the progress
please, was it planned for version 2? Is that a long way off still?

Thanks

Iain (William Hill)

**Comment by RaiMan** [comment]
with the current 1.1.0 pre-final you at least can add a location in the net to the image path.
This lets you access images at runtime.
You are responsible yourself to get the images uploaded somehow.

see the javadocs http://nightly.sikuli.de/docs/
especially: http://nightly.sikuli.de/docs/org/sikuli/script/ImagePath.html#addHTTP-java.lang.String-

**Comment by wakeyowl** [comment]
OK thanks Rai, I will pull down the source again and try updating our
framework constructor again.

Iain
