### ISSUE TITLE
capture method explanation

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#109]
Can someone explain me how to use `capture` method? 
I'm trying to take a screenshot of a region with the following `jruby` code
```
s = Screen.new
img = s.capture()
print img
```
output:
`org.sikuli.script.ScreenImage@5700d6b1`

As per documentation, it says it should return the path of the file saved.
As I can see it's printing the memory address.
How do I save it on local disk?

**Comment by RaiMan** [comment]
Since you are posting here, you seem to use 1.1.0.

The javadocs of class ScreenImage tell you what you need:
http://nightly.sikuli.de/docs/index.html

**Comment by rstormsf** [comment]
Perfect! 
`img.getFile()` works!
