### ISSUE TITLE
Sikuli Clicking issues

### ISSUE THREAD

**Issue by kotipally** [RaiMan/SikuliX-2014#114]
HI Raiman,

Good Morning........!

while clicking the sub menus directly from Sikuli ide or tool run button, its working 100% fine, but while running in command prompt its not working correctly.

issue:-

when the mouse moves from the menu to the sub-menu item, its moving perfectly to exact image location and clicking perfectly at same location but before clicking the sub-menu, sub-menu disappears and then clicking after disappears target(sub-menu) at that location(final result is not clicking on the sub-menu, its clicking on the main gui due to sub-menu disappears)

**Comment by RaiMan** [comment]
I do not understand.

**Comment by kotipally** [comment]
hi Raiman,

the below link, same bug i am getting for different scenario. so how to avoid red circles around mouse click.

https://bugs.dogfood.paddev.net/sikuli/+bug/941883

please help me

**Comment by RaiMan** [comment]
do not use the slow motion run.
You might explicitly switch it off:
Settings.setShowActions(False)

**Comment by kotipally** [comment]
Hi RaiMan,

Here I am explaining clearly my issue:-

Right now I have integrated Sikuli-Robot framework as per below link.

http://blog.mykhailo.com/2011/02/how-to-sikuli-and-robot-framework.html

so my code from Sikuli tool, I don’t have any issues to click context menus. 

But when I am running with commands which they are given(i.e from above link), I have observed that I am unable to click context menu(main menu to sub menu).

Commands are “C:\work\> robottest.bat robot_suite\verify_operations.txt” 
					or 
		
		java -jar "C:\Program Files\Sikuli X\sikuli-script.jar" calc.sikuli

issue here is, I saw mouse moving to exact location and getting some red circles around mouse, at that time sub menu(context menu) missing, after that my mouse clicking after submenu missing. 

So before clicking the mouse, due to some red circles around mouse, object missing and then clicking after missing the object.

Please help me on this and refer above link.

**Comment by RaiMan** [comment]
You are using the obsolete version 1.0RC3.
I do not support this any longer with such system or integration problems.

Come back, if you get the same problems with the version 1.1.0
BTW: look here
https://github.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration

**Comment by kotipally** [comment]
Right now i am using Sikuli r930. 

i think so this is latest version, if it is old, please correct me.

**Comment by RaiMan** [comment]
Since you posted here (current development repo of version 1.1.0), I thought you knew, what you are doing. 
RC3 is the state of Sikuli from 3 years ago.

**Comment by mnergis** [comment]
I am using sikulix ide and I didn't click submenu. Also I didn't clip submenu.
