### ISSUE TITLE
Region.highlight() removes focus on Windows

### ISSUE THREAD

**Issue by aguelle** [RaiMan/SikuliX-2014#115]
- Windows 7 64Bit
- Java 7

Open a combobox with Sikuli from a Java program (this makes some effort to reproduce, sorry in advance)
Highlight the match. -> The combobox will be closed immediately.

I have also seen that screen.highlight() hides windows and brings them back afterwards. 

On Macintosh all behaves as expected.

**Comment by RaiMan** [comment]
Yes, confirmed.

will not be fixed in 1.1.0.

In version 2 I will find a better solution for doing runtime annotations.
