### ISSUE TITLE
onappear(),this API how to use in java

### ISSUE THREAD

**Issue by jiangjinpeng21** [RaiMan/SikuliX-2014#116]
onappear(),this method how to use in java ,could you give me some example?
i found no example on the internet,

**Comment by sskuts** [comment]
I believe the first place you want to search examples at is the official sikulix repository:
https://github.com/RaiMan/SikuliX2/blob/master/sikulixtensions/RemoteServer/src/main/java/com/sikulix/remoteserver/wrapper/RemoteDesktop.java

**Comment by jiangjinpeng21** [comment]
thanks
