### ISSUE TITLE
[error] ResourceLoader: check: Terminating: The jar was not built with setup nor can the libs be exported from classpathUse + -question- find() method

### ISSUE THREAD

**Issue by Fanch-** [RaiMan/SikuliX-2014#117]
Hello,

I'm trying to export my previous sikuli functions to sikuliX(1.1.0-SNAPSHOT).

Firstly, I would like to know -if possible, I see you are busy- when the find function() will work with Image -maybe in 2.0?- ([error] Image: find: not implemented yet), because I find this way a lot more intuitive (Thank you for your work).

Secondly, while the previous implementation is in progress, I would like to know how tu use the find function with new objects : because find() on Finder/ImageFinder objects return a string, and I would like to get back the Match -as for *Image.find()*- to use getScore() function. What does **return null -if find setup not possible-** mean ? -from javadoc-. 
Is **setup** corresponding to a **match** object?

And thirdly, the issue, here a simple function : 

    public double getScoreBetween2Pictures(Image Img, Image Img2) {
        Debug.setDebugLevel(3);
        Finder fd = new Finder(Img);
        // or ImageFinder f1 = new ImageFinder(Img);
        String res = fd.find(Img2);
        //return res.? 
        //return Img.find(Img2).getScore(); when implemented
    }

I have this error when I try to create a sikuliX Finder object :
**From IDE : **

[debug] ResourceLoader: SikuliX Package Build: 1.1.0 2015-01-16_01:15nightly
[debug] ResourceLoader: check: The jar in use is some sikulixapi.jar
(pathToSikulix)/1.1.0-SNAPSHOT/sikulixapi-1.1.0-20150116.001551-75.jar
[debug] Sikulix: addToClasspath: (pathToSikulix)/1.1.0-SNAPSHOT/sikulixlibslux-1.1.0-20150116.001551-75.jar
[error] Sikulix: does not exist - not added
[error] ResourceLoader: check: Terminating: The jar was not built with setup nor can the libs be exported from classpath!
(pathToSikulix)/1.1.0-SNAPSHOT/sikulixapi-1.1.0-20150116.001551-75.jar
[error] ***** Terminating SikuliX after a fatal error 999 *****
It makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.
[debug] Sikulix: cleanUp: 0

**Maven command (Not a valid libs dir for SikuliX? I'll check again installation on website, I might missed somethng) : **

[debug] ResourceLoader: SikuliX Package Build: 1.1.0 2015-01-16_01:15nightly
[debug] ResourceLoader: check: The jar in use is some sikulixapi.jar
(pathToSikulix)/sikulixapi/1.1.0-SNAPSHOT/sikulixapi-1.1.0-SNAPSHOT.jar
[debug] Sikulix: addToClasspath: (pathToSikulix)/sikulixlibslux/1.1.0-SNAPSHOT/sikulixlibslux-1.1.0-SNAPSHOT.jar
[debug] ResourceLoader: check: we are running on arch: amd64
[debug] ResourceLoader: check: using Java at: (pathToJre)/jdk1.7.0_75/jre/
[debug] ResourceLoader: check: Exists libs folder at location of jar? YES: (pathToSikulix)/sikulixapi/1.1.0-SNAPSHOT/
[debug] ResourceLoader: checkLibsDir: trying: (pathToSikulix)/sikulix/sikulixapi/1.1.0-SNAPSHOT/libs
[error] ResourceLoader: checkLibsDir: Not a valid libs dir for SikuliX (amd64): (pathToSikulix)/sikulixapi/1.1.0-SNAPSHOT/libs
[debug] ResourceLoader: check: libs dir is empty, has wrong content or is outdated
[debug] ResourceLoader: check: Trying to extract libs to: (pathToSikulix)/sikulixapi/1.1.0-SNAPSHOT/libs
[debug] FileManager: deleteFileOrFolder: filtered: 
(pathToSikulix)/sikulixapi/1.1.0-SNAPSHOT/libs
[debug] ResourceLoader: extractLibs: Found 0 Files in META-INF/libs/linux/libs64/

(pathToSikulix) = /home/fanch/.m2/repository/com/
Possible duplication of issue #110 .
I use maven to import libs -linux-. And yes my libs dir is empty, should I import them manually?

**Comment by RaiMan** [comment]
--1. sorry for not being consistent in the java docs: all classes Image…. except ImagePath are not for public use currently and even not later with any 1.1.x. for that you have to wait for version 2.
I will add respective warnings to the classes, that should not be used currently in user programs.

--2. the correct usage of the Finder class (see docs) is:
Finder f = new Finder(baseImage);
f.find(targetImage); // a return value of null signals, that the image file could not be loaded
Match m = null;
if (f.hasNext()) {
   m = f.next();
}
if (m != null): // now we can continue with the match

--3. your sikulixapi version
in standard Maven manner the intended use is:

	<repositories>
		<repository>
      
			<name>com.sikulix</name>
			<id>com.sikulix</id>
			<url>https://oss.sonatype.org/content/groups/public</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			<version>1.1.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

If you use it this way, the sikulixlibslux.jar should be automatically downloaded and be on class path at runtime, when running with Maven.

Nevertheless I have to check, why not the latest sikulixapi from this morning is on OSSRH, but still the version from mid january.
You should try again tomorrow.

**Comment by Fanch-** [comment]
Ok, thank you, I will.

**Comment by RaiMan** [comment]
You might try already now. now version is online (snapshot version: 20150325.143910-76)

**Comment by Fanch-** [comment]
It seems better; I can create a Finder object.

Now I have this error : 

[error] RunTimeAPI: loadLib: libVisionProxy.so not usable: 
java.lang.UnsatisfiedLinkError: /home/fanch/.Sikulix/SikulixLibs_201503260100/libVisionProxy.so: libopencv_core.so.2.4: cannot open shared object file: No such file or directory

When I use : 

        Finder f = new Finder(-org.sikuli.script Image-);
        f.find(-org.sikuli.script Image-);

**Comment by RaiMan** [comment]
Guess you did not read the http://sikulix.com/quickstart

**Comment by Fanch-** [comment]
My bad, just install the libs for linux did it. It works great, even with intellij. Thank you for your work, I look forward to the transparency feature with Sikulix 2.0.

**Comment by RaiMan** [comment]
Thanks for feedback.
