### ISSUE TITLE
can sikulixapi.jar use on jdk:1.6.0_43

### ISSUE THREAD

**Issue by jiangjinpeng21** [RaiMan/SikuliX-2014#120]
i use sikulixapi.jar in my java project,
when 
Screen s = new Screen();
there throw exception:

Exception in thread "main" java.lang.NoSuchMethodError: java.lang.System.lineSeparator()Ljava/lang/String;
	at org.sikuli.script.RunTime.<clinit>(RunTime.java:83)
	at org.sikuli.script.Region.<clinit>(Region.java:28)

i found there is error in org.sikuli.script.RunTime.java     69
can not find  System.lineSeparator();
my jdk:1.6.0_43

can sikulixapi.jar use on jdk:1.6.0_43

**Comment by jiangjinpeng21** [comment]
must i use jdk:1.7

**Comment by RaiMan** [comment]
--- must i use jdk:1.7
no, I want to stay Java 6 compatible with 1.1.x

Just fixed the above problem.

I will run a nightly build now. 
Should be available latest in one hour.
