### ISSUE TITLE
[1.1.0] Sikuli  'exists' issue with Pattern(invalid image) - fixed 2015-04-17+

### ISSUE THREAD

**Issue by LuffyAutomation** [RaiMan/SikuliX-2014#122]
Hi RaiMan, 
First of all, thanks for all your great work on Sikuli, it is very useful tool.
But I found an issue with Sikuli 1.1.0 - NightlyBuild416.
<b>Code:
#1. def action_check(imgName, seconds=3, similarity=0.7):
#2.		 s = Pattern(imgName).similar(similarity)
#3.		 exists(s, 3)</b>
If I delete the captured image file (so the imgName is no longer valid) and run this code, this script will hang on at #3. 
This issue does not occur if I use Sikuli 1.01.

Please help me, thanks in advance.

**Comment by RaiMan** [comment]
what exactly means
--- this script will hang on at #3. ???

symptoms, error messages?

**Comment by RaiMan** [comment]
ok, found out my self: loops endlessly.

will fix it as soon as possible.

**Comment by RaiMan** [comment]
fixed with tomorrow's nightly.

thanks for finding.

**Comment by LuffyAutomation** [comment]
Thank you very much. I am looking forward to this new release.

**Comment by RaiMan** [comment]
available now
