### ISSUE TITLE
cmd script can not find Java in Windows PATH

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#125]
It is a user fail I think, that supplied cmd file is not able to use java from PATH and fails with error.

To detect that java is available and executable, it is possible to use [this batch trick](https://github.com/kennethreitz/python-guide/blob/master/docs/make.bat#L49):

```
REM Check if Java is available
java 2> nul
if errorlevel 9009 goto no_java
goto java_ok
```

**Comment by RaiMan** [comment]
Thanks. Good point.
added to runsikulix.cmd - available 2015-04-20+

**Comment by techtonik** [comment]
Cool. Do you have a release plan to know when new binaries with can be downloaded from https://github.com/RaiMan/SikuliX-2014/releases ?

This https://github.com/RaiMan/SikuliX-2014/milestones can be a handy.

**Comment by RaiMan** [comment]
maybe next week the final 1.1.0.

Launchpad: yes.
