### ISSUE TITLE
Need something with "Keyboard" word in tutorials list

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#126]
In particular, need to know how to enter `Alt-<Key>` fast for navigating through menus. That's more reliable.

**Comment by RaiMan** [comment]
see docs:
http://sikulix-2014.readthedocs.org/en/latest/keys.html#key-constants

**Comment by techtonik** [comment]
Unfortunately, this doesn't describe how to select/click menu items in scripts. The info there is for already experienced users. There is no intro and no usage example for ALT modifier key (which is not the same as KeyModifier.ALT, which is confusing).

**Comment by RaiMan** [comment]
A key is called a modifier key, when it is used in conjunction with other keys by pressing and holding it while typing the other keys.
The keys used most commonly as modifier keys are SHIFT, ALT (left alt key, CTRL (might be strg on Windows) and the CMD key (Apple key on OS X).
On Windows you additionally have the Windows key and the alt key on the right.

the plain type command has 2 parameters:
parameter 1: the keys, that should be pressed/released one after the other
parameter 2: the modifier keys, that alltogether should be pressed and held during the typing and released at the end.

For parameter 2 there are 2 options:
old version (kept for upwards compatibility): KeyModifier.XXX
new version: (a key is a key ;-): Key.XXX

So in your case, it does not matter, what the key presses are used for (SikuliX does not know anything about the GUI anyway).

`Alt-<Key>` simply is
`type(<Key>, Key.ALT)`

in any case.

**Comment by techtonik** [comment]
This info is better read from tutorial rather than from Github issue.

> Alt-<Key> simply is
> type(<Key>, Key.ALT)

The docs here - https://sikulix-2014.readthedocs.org/en/latest/keys.html#special-keys - say that `Key.ALT` can not by used with `type`.

**Comment by RaiMan** [comment]
ok, you are right ;-)

I will adjust the docs. thanks.

**Comment by techtonik** [comment]
That would be useful. =)

**Comment by RaiMan** [comment]
please check the changes i made. thanks.

**Comment by techtonik** [comment]
Good. I'd remove `KeyModifier` from example, because people like me often just copy code from examples without reading anything at all. It feels like the type() function reference should be linkified.

And type() docs should backlink to modifier keys description. https://sikulix-2014.readthedocs.org/en/latest/region.html#Region.type

**Comment by RaiMan** [comment]
thanks for feedback.

good points.

**Comment by techtonik** [comment]
no problem ;)

**Comment by RaiMan** [comment]
I think, now it should be sufficient.
