### ISSUE TITLE
"Run from here"

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#127]
It will be very useful for debugging to run stuff from the middle of the script, or have "cell" concept like in scientific scripts.

**Comment by RaiMan** [comment]
Might be, but this is far beyond, what the SikuliX IDE will ever support.

If you need to have such things, then you have to structure your scripts into modules, classes and/or functions. This is the "cell" concept of Python and other comparable scripting languages.

If you need some kind of debugging and this is not sufficient, then you have to use an IDE, that supports debugging like Eclipse/PyDev or others.

**Comment by techtonik** [comment]
Why not to add "run from this line"?

**Comment by RaiMan** [comment]
I could add such an option, but this only works in situations, where the script does not have any "history" up to this point (like assigning  values to variables or other things done before that line, that are needed after that line).

I still think, that dividing a script into portions packed in  def()s, that are then called as needed, is sufficient and helps to have your workflow clearly structured.

**Comment by techtonik** [comment]
Yes, but that means I have to comment and uncomment the stuff all the time, which is not convenient. I ended up splitting the script into several small files and run each other separately.

**Comment by RaiMan** [comment]
the usual Python way, to solve that:

def setup():
     # some code
def step1():
     # some code
def step2():
    # some code
def step3():
     # some code
def step4():
     # some code
def teardown():
     # some code

setup()
step1()
step2()
step3()
step4()
teardown()

if you would use functions with parameters, you could even fine tune, what is done in each step.

with the latest 1.1.0 you could even do this with your files from one script:

runScript("firstOne")
runScript("secondOne")
runScript("thirdOne")
runScript("lastOne")
