### ISSUE TITLE
Jython 2.7rc2 does not work on Windows with Java 7

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#128]
Just tried using latest jython 2.7rc2 version on Windows with JDK7 - doesn't work :-(
2.7b4 - works fine. 
FYI - anybody who needs jython2.7b4 - have to find it on maven repo
[jython-installer-2.7-b4.jar](http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7-b4/jython-installer-2.7-b4.jar)

**Comment by RaiMan** [comment]
Thanks for the info, but what happened? Error messages?

For use with Sikuli it is sufficient to use the standalone jar (no installation needed):
[jython-standalone-2.7-b4.jar](http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7-b4/jython-standalone-2.7-b4.jar)

This is also the one, that currently is bundled with Sikulix (sikulix.jar).

**Comment by rstormsf** [comment]
it was raising the error 
```
[error] RunTimeINIT:  *** terminating: no valid Java context for SikuliX available (java.security.CodeSource.getLocation() is null)
```

just noticed rc3 came out today, maybe I want to test on that one.

**Comment by RaiMan** [comment]
That is interesting, because the error should have nothing to do with the used Jython version (an early startup problem using Sikuli features).
So it would be helpful, to get information of your setup (class path, shell script, ...)
