### ISSUE TITLE
not sure how to get this running on a mac

### ISSUE THREAD

**Issue by knightjacky** [RaiMan/SikuliX-2014#130]
i run `./runSetup` and i get an error saying `Setup/target/*plain.jar`

**Comment by RaiMan** [comment]
Why do you want to run a setup from inside the sources?
There is a setup jar downloadable from the nightly page.

... or did you make any changes, that you want to test?

Nevertheless: just revised the runsetup script. it now works when run in the root of the project.
In all cases you have to run a clean install at the root level.

If not: just double click on the `Setup/target/setup-1.1.0-forsetup.jar`
 or run the setup module from inside Netbeans/Eclipse.

On Mac, the setup results when running this way are stored in 
`~/Library/Application Support/Sikulix/SikulixSetup`

**Comment by RaiMan** [comment]
no more activity
