### ISSUE TITLE
Multiple Monitor SelectRegion Issues

### ISSUE THREAD

**Issue by Zykr** [RaiMan/SikuliX-2014#137]
When using the selectRegion function without specifying a screen, the selection interface shows up on both screens under Windows 7, but on Mac OS 10.10 it only shows up on the primary screen.

If you specify the screen using Screen(1).selectRegion() then the picker shows up on screen 1 but displays a screenshot of the primary display.

Using the highlight() function on the region shows up on the correct screen, sometimes showing a section of screen 0, and sometimes showing the correct contents in the bounding box.

The capture function works as expected despite the wrong image being displayed when selecting the area, as confirmed by opening saved pictures, but the screenRegion.exists() check always returns “None” when the screen is set to 1.

All of these behaviors are observable in the following code snippet with slight modifications to the first line.

Code Example:
```python
screenRegion = Screen(1).selectRegion()
refImage = capture(screenRegion)
match = screenRegion.exists(Pattern(refImage), 0)
print(screenRegion)
print(refImage)
print(match)
```

**Comment by RaiMan** [comment]
Since I can only test that on Monday:
Does this happen with the latest build from today or even with a fork of the current repo?

**Comment by Zykr** [comment]
This issue happens with the nightly from the 7th,
20150507.231008
and with a fork of the repo from the commit at
Fri May 8 13:44:09 2015 +0200
taken at 17:47.

**Comment by RaiMan** [comment]
ok, thanks.
I am already on track to fix the problem.

**Comment by RaiMan** [comment]
should be fixed now (2015-05-15+)
