### ISSUE TITLE
Offset does not work since latest commit

### ISSUE THREAD

**Issue by d97ulf** [RaiMan/SikuliX-2014#138]
I am using 1.1.0-SNAPSHOT via maven updated on a daily basis. I noticed that our Java based tests are broken since a couple of days back when it comes to clicking with an offset (i.e. find image, click with offset):

Pattern p = createPattern("myImage");
screen.doubleClick(p.targetOffset(35, -105));

Seems like Sikuli is clicking without using the offset. I don't know if it is stochastic or if it happens all the time.

Looking at the code commits, I notice that changes have been made that could possibly affect this.

In addition, I tried to roll back to 1.1.0-Beta4-SNAPSHOT, but there seems to be some dependency issue in Maven:

Failed to execute goal on project autotest: Could not resolve dependencies for project xxx: The following artifacts could not be resolved: com.sikulix:sikulixlibswin:jar:1.1.0-Beta4-SNAPSHOT, com.sikulix:sikulixlibsvision:jar:1.1.0-Beta4-SNAPSHOT: Could not find artifact com.sikulix:sikulixlibswin:jar:1.1.0-Beta4-20140910.063220-15 in com.sikulix (https://oss.sonatype.org/content/groups/public) -> [Help 1]

Tried to run Maven with -U option (to force download), and it seems like the correct jars are downloaded, but it does not work anyway...

**Comment by RaiMan** [comment]
Thanks for the pointer.

Arrrg, stupid, careless mistake.

Is fixed now. I will trigger a build, so it will be available in about one hour.

**Comment by d97ulf** [comment]
Great - thanks for the rapid response and fix! I will look out for the update.
