### ISSUE TITLE
[1.1.0] Sikuli 'image identification' issue

### ISSUE THREAD

**Issue by LuffyAutomation** [RaiMan/SikuliX-2014#139]
Hi,  RaiMan
Hope you have a nice day.
I think I found an issue with latest Sikuli1.1.0: 
Sometimes, wrong targets were identified by Sikuli.

Example1: find(img1) or click(img1)
![img1](https://cloud.githubusercontent.com/assets/11975800/8002977/caf4362c-0ba5-11e5-954f-414c6d60d54c.png) img1.png
Sikuli may incorrectly locate on this kind of image. >> img1_WrongTarget.png. (Red area was found/ clicked incorrectly by Sikuli)
![img1_wrongtarget](https://cloud.githubusercontent.com/assets/11975800/8003182/ceca8a60-0ba7-11e5-883b-49371c9b4bc7.png)  img1_WrongTarget.png(I marked red box.)
-------------------------
![img1_wrongtarget](https://cloud.githubusercontent.com/assets/11975800/8002979/d1d53dc4-0ba5-11e5-9f2d-870bf140d640.png)  img1_WrongTarget.png(It can be used for reproducing issue. But it is better reproduce it with real UI.)

Example2:
s = Pattern(img2).similar(0.8)
if exists(s, 1):
&nbsp;&nbsp; click(s)
![img2](https://cloud.githubusercontent.com/assets/11975800/8002996/feadb830-0ba5-11e5-80aa-0de003b92feb.png) img2.png
Sikuli may incorrectly click this kind of image.> > img2_WrongTarget.png. (Red area was clicked incorrectly by Sikuli)
(.similar(0.9) and .similar(1) also won't help.)
![img2_wrongtarget](https://cloud.githubusercontent.com/assets/11975800/8003207/07e55ae6-0ba8-11e5-8a9b-9bf1ef4a0826.png)  img2_WrongTarget.png(I marked red box.)
-------------------------
![img2_wrongtarget](https://cloud.githubusercontent.com/assets/11975800/8003021/4cb1579e-0ba6-11e5-87cd-d6afaeec0e82.png)  img2_WrongTarget.png(It can be used for reproducing issue. But it is better reproduce it with real UI.)

Debug_OS: 10.10.3 and 10.8.5
Please help to check if this is an issue. Thanks. :P

**Comment by RaiMan** [comment]
Yep, this might happen in the IDE when repeating scripts, where the image (like your img1) was already found before (wrong, but with a score of say 0,77).
Now you start to raise the min similarity, to get correct matches, but it still finds the image in a wrong place.
See https://bugs.launchpad.net/sikuli/+bug/1461533 and the related question for more information and workarounds until fixed.

Another workaround is to put 
Image.reset()

at the beginning of the script until this is fixed and you are repeating the same script with modified Pattern settings.

**Comment by LuffyAutomation** [comment]
Thanks for your quick answer. I'll try it.

**Comment by LuffyAutomation** [comment]
This issue do occurs on first time.
Reproduce steps:
1. Restart the Mac OS. (Just for making a clean ENV. >> The Right target was not found before.)
2. Open the img2_WrongTarget.png.
4. Run click(img2Path) [just this one line in IDE]
Result: the wrong target img2_WrongTarget.png is clicked. 

Additional Info:
1. No matter from where opening the img2_WrongTarget.png on Desktop, it can be clicked.
2. Open Right target img2.png and Wrong target img2_WrongTarget.png at the same time, the wrong target is clicked instead of right target.

Hope this info helpfully.

**Comment by RaiMan** [comment]
- restarting the SikuliX IDE is enough (no need to restart OS X)

--- 2. Open the img2_WrongTarget.png.
I do not understand what you mean by "open" and what image is it?

--- 4. Run click(img2Path) [just this one line in IDE]
what image is img2Path?

**Comment by LuffyAutomation** [comment]
Oh, I'm sorry for these confusions, my english is not good. :p. Thanks for your patience.

<u>For [--- 2. Open the img2_WrongTarget.png.  I do not understand what you mean by "open" and what image is it?]:</u>
It means double-clicking the [img2_WrongTarget.png] to make it displaying on the desktop.
(I just simply opened the [img2_WrongTarget.png] from Preview app of Mac OS to debug instead of real target UI.)

The [img2_WrongTarget.png] is 
![img2_wrongtarget - copy](https://cloud.githubusercontent.com/assets/11975800/8048848/2a9ba28c-0e89-11e5-8048-9dd88f6ca5b5.png)

<u>For [--- 4. Run click(img2Path) [just this one line in IDE]  what image is img2Path?]:</u>
The [img2Path] is the path of [img2.png]. For example: "/Users/zzz/Desktop/img2.png"
So [<b>click(img2Path)</b>] means <b>click("/Users/zzz/Desktop/img2.png")</b>

The [img2.png] is
![img2](https://cloud.githubusercontent.com/assets/11975800/8048882/869cb116-0e89-11e5-803f-49ca2cfb7f4e.png)

The result is:
After running <b>click("/Users/zzz/Desktop/img2.png")</b>, <b>the img2_WrongTarget.png was clicked</b> even the right [img2.png] displaying on the desktop at the same time.

**Comment by RaiMan** [comment]
You cannot use the img2.png as such, you have to use a Pattern with a high similarity.
try: click(Pattern("img2.png").similar(0.95))

**Comment by LuffyAutomation** [comment]
Thanks for your help. I've solved my problem.
One last question here: 
Why I have to use a Pattern for img2.png?
As I see, img2.png and img2_WrongTarget.png are completely different, and click(*.png) works well on many other png files

**Comment by RaiMan** [comment]
--- Why I have to use a Pattern for img2.png?
... because the pixel pattern apparently matches other places on the screen as well with a similarity >0.7, which is the default, when not using Pattern().similar().
using Pattern().similar() besides restricting the search region is the only way, to match what you expect.
might be helpful to understand: 
http://sikulix-2014.readthedocs.org/en/latest/basicinfo.html#sikulix-how-does-it-find-images-on-the-screen

**Comment by LuffyAutomation** [comment]
Thank you very much.
