### ISSUE TITLE
API used for screenshots

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#140]
Hi RaiMan. I was browsing StackOverflow and stumbled upon this question - https://stackoverflow.com/questions/2447172/getting-window-screenshot-windows-api

What is the API that Sikuli uses for taking screenshots on different platforms? It concerns me primarily for two reasons:

1. performance
2. alternative inputs

The first would be useful to measure overhead and delay for screen taking and screen processing separately. For the second, I wonder if I can route VNC session to Sikuli.

**Comment by RaiMan** [comment]
In SikuliX the Java Robot class is used to take screenshots and the result is an in-memory representation of the image pixels (Java BufferedImage class).
This action (screen taking) takes some milliseconds depending on the image size. 

What you mean by "screen processing" can only be the find op done on this screenshot.
If you have a screenshot of WS x HS pixels and an image of WI x HI pixels then the cost of processing roughly is:
(WS*HS - WI*HI) * WI*HI * BASEOP

where BASEOP is the evaluation of the differences of 2 images of size WI*HI (which results in the score value at that pixel in the screenshot)

The timing can be described roughly as:
a find op is faster
- the smaller the screenshot is
- the more equal the sizes of shot and image are

Which leads to the general recommendation, to restrict the search region as often as possible to the smallest possible area.

About VNC and Sikuli, you have to scan the Internet (even StackOverflow has some questions/answers about that).

**Comment by techtonik** [comment]
Thanks. Do you have plans to embed some benchmarks into Sikuli to measure all this stuff?

**Comment by techtonik** [comment]
The Robot procedure is here - https://github.com/RaiMan/SikuliX-2014/blob/b869c87f8437c2eff31ff0bdd9cbb8678bebff4a/API/src/main/java/org/sikuli/script/RobotDesktop.java and the docs are here https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html#createScreenCapture(java.awt.Rectangle)

It seems that this API is unable to capture hidden and minimized windows.

**Comment by RaiMan** [comment]
Generally this Java Robot feature createScreenCapture will only capture what currently is visible on the screen (hence only the pixels in the screen buffer). It knows nothing about windows and other GUI elements. So hidden or minimized does not mean anything in this context.

**Comment by RaiMan** [comment]
@techtonik asked: embed some benchmarks into Sikuli to measure all this stuff
this is already available now.
```
m = find(someImage)
print m
```
prints something like:
M[14,44 106x35]@S(S(0)[0,0 1440x900]) S:1.00 C:67,61 [303/302 msec]

where 
M is the match region
S( the screen where it is on
S: the similarity score
C: the center of the match
[n/m msec] search time: n over all, m of the last search repetition

If the image is still in the same place when run again you get much shorter times due to the CheckLastSeen feature:
M[14,44 106x35]@S(S(0)[0,0 1440x900]) S:1.00 C:67,61 [31/31 msec]

**Comment by techtonik** [comment]
I was thinking about some command line mode that runs some colorful patterns, tries to find them and then outputs log in some specific format. So that it could be run on different systems for comparison.

**Comment by RaiMan** [comment]
I do not understand what you need????

Just setup a script and run it from command line.

**Comment by techtonik** [comment]
The previous post if about a benchmark. Benchmark should be run several dozen times to get reliable results. And the output should be easy to compare. It is also interesting to know what takes more time - taking screenshot, converting it to OpenCV format or pattern matching?

**Comment by RaiMan** [comment]
```
loops = 100
start = time.time()
for n in range(loops):
    find(someImage) # see **comment
elapsed = time.time() - start
oneFind = int(elapsed/loops)
print "one find: %d msec" % (oneFind)
```
**comment
in this line you might call some function, that does special things

--- It is also interesting to know what takes more time - taking screenshot, converting it to OpenCV format or pattern matching?
Not clear what you mean:
pattern matching is exactly, what SikuliX does: searching one image in another image. 
If you search on the screen, another image must be a screenshot.

**Comment by techtonik** [comment]
The whole processing loop is:

* take screenshot (time between Robot call and returned image)
* convert to OpenCV format used for matching (the image data is converted in memory, right?)
* match image (time between call to OpenCV and return)

**Comment by techtonik** [comment]
It is interesting to evaluate performance on all three phases.

**Comment by RaiMan** [comment]
I added some more detailed timing information, that produces output like this for one find op:
```
[FindProfiling] Screen.capture [1440 x 900]: 27 msec
[FindProfiling] createCVMat [1440 x 900]: 156 msec
[FindProfiling] createCVMat [105 x 32]: 1 msec
[FindProfiling] Region.doFind final: 208 msec
```
in this case the image is found on first try.

if it is not found on first try (waiting for), you get something like this:
```
[FindProfiling] Screen.capture [1440 x 900]: 20 msec
[FindProfiling] createCVMat [1440 x 900]: 119 msec
[FindProfiling] createCVMat [105 x 32]: 1 msec
[FindProfiling] Region.doFind repeat: 396 msec
[FindProfiling] Screen.capture [1440 x 900]: 24 msec
[FindProfiling] createCVMat [1440 x 900]: 118 msec
[FindProfiling] Region.doFind repeat: 397 msec
[FindProfiling] Screen.capture [1440 x 900]: 21 msec
[FindProfiling] createCVMat [1440 x 900]: 107 msec
[FindProfiling] Region.doFind repeat: 433 msec
[FindProfiling] Region.doFind final: 17 msec
```

The information is not really separated according to your mentioned steps and has to be read like this:

- when found on first try 
 - [FindProfiling] Screen.capture: capture the given screen region to a BufferedImage (inMemory)
 - [FindProfiling] createCVMat: convert this BufferedImage into the internal OpenCV format (CVMat)
 - [FindProfiling] Region.doFind final: the complete find op including the above steps, which means that the time for OpenCV matchTemplate() search op is the rest after subtracting the steps before (in the example: 208 - 27 - 156 - 1 = 124 msecs)

- when found after repetitions (waiting)
 - the final time does not seem to be comparable to the first try situation (still under evaluation)

The challenge:
currently the timing cannot be taken consistently (different places and classes in the code, not thread safe). It only gives some hint about the different steps and might allow to compare the same situation on different systems or different setups.
It is not possible anyway to do anything about that timing currently, without changing the SikuliX code.

... and this will be done with version 2 anyway.

BTW: to switch the above output on and off:
Settings.FindProfiling = True/False

**Comment by RaiMan** [comment]
sorry, from tomorrows build only ;-)

**Comment by techtonik** [comment]
So, this is for one **find(someImage)** call. Very nice. =)

1. Looks like `createCVMat [105 x 32]: 1 msec` is for `someImage` - it might be possible to convert it to CMat before of screen capture cycle and cache it. Kind of 'screen literal' that can be 'compiled' statically. Interesting if CVMats can be serialized for caching and/or processing outside of SikuliX process?

2. For comparison Is it possible to store this profiling data for **finf** in some structured data format, that can be compared between platforms and preserve last few (~100) in memory queue, and export if requested? Like this YAML-like format:
```
find:
  init:
    createCVMat: [105 x 32] 1 msec
  repeat:
    Screen.capture: [1440 x 900] 20 msec
    createCVMat: [1440 x 900] 119 msec
    Region.doFind: 396 msec
  repeat:
    Screen.capture: [1440 x 900] 24 msec
    createCVMat: [1440 x 900] 118 msec
    Region.doFind: 397 msec
  repeat:
    Screen.capture: [1440 x 900] 21 msec
    createCVMat: [1440 x 900] 107 msec
    Region.doFind: 433 msec
  complete:
    sum: 17 msec
```

**Comment by techtonik** [comment]
Those `repeat`s above can then be visualized with [Box plot](https://en.wikipedia.org/wiki/Box_plot)

**Comment by RaiMan** [comment]
You might play around with it a little. I will not do anything else with it in the moment.
Only with version 2 I will go into that again (including CVMat caching instead of BufferedImages and a faster way to get from screenshot to CVMat)

**Comment by techtonik** [comment]
Thanks for the feedback. I will get back to it one day.
