### ISSUE TITLE
runsikulix vs sikulix.jar

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#143]
```
-rwxrw-r--  1 techtonik techtonik      594 Jun 19 12:49 runsikulix
-rwxrw-r--  1 techtonik techtonik 44527744 Jun 19 12:49 sikulix.jar
```
Both are executable. What's the difference?

**Comment by RaiMan** [comment]
runsikulix: a command script (usually to be used with parameters to run scripts from command line)
sikulix.jar: the java jar file to be run with Java (can usually be double clicked to start the IDE)

**Comment by techtonik** [comment]
Both are executable. Why need both? It is confusing. Why sikulix.jar can not be run with parameters from command line?
