### ISSUE TITLE
Visuals are gone

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#145]
I remember when first Sikuli site was straight to the point, with more pictures than text, and I liked it. Not the http://www.sikuli.org/ but this one - http://web.archive.org/web/20100123201404/http://sikuli.org/

**Comment by RaiMan** [comment]
Please be more specific, what you are missing.
The mentioned pages are no longer maintained (actually stopped when the former developers left true project after 1.0-rc3 in 2012).
The official SikuliX page now is: http://sikulix.com

**Comment by techtonik** [comment]
I said everything already. =) Too much text. People do not read and do not understand what this site is about. The former one - http://web.archive.org/web/20100123201404/http://sikuli.org/ was much moore intuitive with no low level Java details that frighten users.

**Comment by techtonik** [comment]
You may test this claim with https://usabilityhub.com/

**Comment by RaiMan** [comment]
I think I have other problems to solve.

**Comment by techtonik** [comment]
I am not surprised.
