### ISSUE TITLE
Sikulix Java Intellij setup

### ISSUE THREAD

**Issue by p-elsie** [RaiMan/SikuliX-2014#149]
Previously someone asked about setting up IntelliJ for SikuliX and the issue was closed without a resolution.  So I spent some time looking at ResourceLoader.java, and then applied Dependency Walker to WinUtil.dll.  

I've now determined the following:

1) ResourceLoader expects a libs folder in the same folder as sikuli-java.jar.  Then it looks at your OS PATH variable to see if it contains that libs folder.  If not, then Sikuli bails with the following message:

[error] ResourceLoaderBasic: checkLibsDir: libs dir is not on system path: D:\SikuliX\libs
[action] ResourceLoaderBasic: checkLibsDir: Please wait! Trying to add it to user's path
[info] runcmd: reg QUERY HKCU 
[info] runcmd: reg QUERY HKEY_CURRENT_USER\Environment /v PATH 
[error] ResourceLoaderBasic: checkLibsDir: Logout and Login again! (Since libs folder is in user's path, but not activated)
[error] Terminating SikuliX after a fatal error! Sorry, but it makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.

2) WinUtil.dll has dependencies on jawt.dll (should be in same libs folder) and more importantly awt.dll, which is part of JAVA.  It is in the bin folder of your JRE.  This bin folder also must be in your path, otherwise (assuming you added D:\SikuliX\libs), you'll get:

[error] ResourceLoaderBasic: loadLib: Fatal Error 110: loading: WinUtil.dll
[error] ResourceLoaderBasic: loadLib: Since native library was found, it might be a problem with needed dependent libraries
D:\SikuliX\libs\WinUtil.dll: Can't find dependent libraries
[error] ResourceLoaderBasic: loadLib: Check, wether a valid Sikuli libs folder is in system path at runtime!
[error] Terminating SikuliX after a fatal error(110)! Sorry, but it makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.

3) IntelliJ doesn't replace %PATH% with the current path.  

So to get SikuliX to run (version 1.1) using IntelliJ (or some other Java IDE, like Eclipse), make sure your Run/Debug configuration includes an override of the PATH variable that includes:

1) The system32 folder (where many DLL files are)
2) The SikuliX/libs folder
3) The bin folder for your JRE (where awt.dll is)

In my case, this worked: C:\windows\system32;C:\Progra~1\Java\jdk1.8.0_45\jre\bin;D:\SikuliX\libs

You shouldn't have to change the path variable for your whole system and then Logout and Login like the error message tells you to - we're not trying to use the Sikuli-IDE, just use the Java API.  

I hope this helps someone else.  It sure is nice to be able to compile and debug your code from within your Java IDE.

**Comment by RaiMan** [comment]
Thanks for the evaluation.

... but this is no longer relevant with 1.1.0:
- at runtime, the dll set, fitting the used Java version's bitness, is exported to a central SikuliX repository on that system
- the path to the libs folder is added on the fly to system path only for this run (Win32 API via bridj)
- the actual awt.dll is copied to the libs folder

With 1.1.0 you do not need anything anymore in system environment for Sikulix to work (either as GUI, from command line or with API usage)

**Comment by p-elsie** [comment]
Thanks for the correction.  I am still using 1.0.1.  Maybe I'll try 1.1 soon.

**Comment by RaiMan** [comment]
Sorry, did not want to correct you: with respect to 1.0.1 you are absolutely right.

I only wanted to point out, that things have changed a bit in 1.1.0
