### ISSUE TITLE
finder - > findAll() regression ?

### ISSUE THREAD

**Issue by Fanch-** [RaiMan/SikuliX-2014#150]
Hello, I would like to know if there was a modification about findAll() function, because it doesn't work for me since a few weeks.

For example, considering this function : 

```java
public static  List<Double> getAllScoresBetween2Pictures(Image baseImg, String targetImg) {
    Finder f = new Finder(baseImg);
    List<Double> scores = new ArrayList<>();
    Settings.MinSimilarity = 0.8;
    f.findAll(targetImg);
    Match m;
    while (f.hasNext()) {
        m = f.next();
        scores.add(m.getScore());
    }
    return scores;
}
```

I get no result, no NullPointerException.
Though if I just replace findAll() by find() for the same comparison,  I get a match, so it doesn't come from the way I manage Images.

(1.1.0-SNAPSHOT)

**Comment by RaiMan** [comment]
Confirmed. Messed something up. Will try to fix it instantly.

Workaround for now:
   //Settings.MinSimilarity = 0.8; //does not make sense anyway
    f.findAll(Pattern(targetImg).similar(0.8));

**Comment by RaiMan** [comment]
fixed with build 2015-07-03+
