### ISSUE TITLE
Log sikuli-ide run messages to a file

### ISSUE THREAD

**Issue by truedays** [RaiMan/SikuliX-2014#153]
Would it be possible to allow for an option. Either in gui preferences or cli argument where I can tell sikuli-ide to record all run "messages" to a file per run?

Also the ability to specify a unique filename format. (ie sikuliproject_1437794829.log or filename_unixtime.log)

**Comment by RaiMan** [comment]
look:
http://sikulix-2014.readthedocs.org/en/latest/scripting.html#writing-and-redirecting-log-and-debug-messages

**Comment by RaiMan** [comment]
http://sikulix-2014.readthedocs.org/en/latest/scripting.html#writing-and-redirecting-log-and-debug-messages
