### ISSUE TITLE
sixulixapi 1.1.0 doesn't work on Yosemite (App.focusedWindow)

### ISSUE THREAD

**Issue by cstacy** [RaiMan/SikuliX-2014#156]
On OSX 10.10.4...

The sikulixapi (nightly build retrieved 2015-0802) doesn't quite work:

My Java program can App.focus("Safari") okay, but  focusedWIndow seems to always return a null Region. The App.getWindow() method is returning the string "!".

Example output:

[log] App.focus:  [-1:Safari]
No focused region in [-1:Safari (!)] Safari

I also tried calling App.focus(n), and App.window(n), and both of those in succession, with -1, 0, 1, 2, and the same thing happens. The App instance apparently never hacks the window.

Approaching the problem a different way, starting with the Screen and searching with an ImageFinder, works correctly. But I don't want to do all that, if I can just go through the App itself.

**Comment by RaiMan** [comment]
ok, I will check that next week, when I am back from vacation.

**Comment by RaiMan** [comment]
works in 1.1.0 final
```
# brings Safari to front
App.focus("Safari")
# highlights Safari's window
App.focusedWindow().highlight(2)
```
