### ISSUE TITLE
Having trouble running self-built instance

### ISSUE THREAD

**Issue by meisjohn** [RaiMan/SikuliX-2014#159]
Cloned latest from GitHub and built using `mvn clean install`.  Everything appeared to have built and I got JARs in the applicable target directories.  

Running Ubuntu 15.04 on an ARM architecture (swapped out libJXGrabKey with copy for the correct architecture.)

Getting this error when I type in `mvn -pl IDE exec:java`

     [error] RunTimeIDE:  *** terminating: JythonScriptRunner: no sikulix....jar on classpath

Available download worked fine.  

Note: This is my first experience with maven, so please be kind. :)

**Comment by RaiMan** [comment]
I am sorry, but apparently using Maven from command line does not work currently (I do not use it, since I do my development and the runs from inside Netbeans, where it works fine).

I have to revise this the next days.

**Comment by meisjohn** [comment]
Thank you for investigating.  I will wait for your patch.

**Comment by RaiMan** [comment]
I did not succeed in making the IDE run with mvn exec:... from command line (classpath problems in any variant).

So currently the only possibility (and this will be the only one for 1.1.0):
- run `´mvn -pl Setup

This will make a silent offline setup with the stuff from the project. The results are found in SikulixAppData/SikulixSetup.

I will change the docs/information accordingly.
