### ISSUE TITLE
got illegal ArgumentException when using function type("inpu.png","笔记本")

### ISSUE THREAD

**Issue by airfer** [RaiMan/SikuliX-2014#160]
As shown in the title，if the second argment of the type function is put in chinese , exception happened , I want to know how to solve this .   Thanks ! 

log info：

[log] TYPE "笔记本"
[error] script [ data ] stopped with error in line 1
[error] java.lang.IllegalArgumentException ( java.lang.IllegalArgumentException: Cannot convert character ? )

**Comment by RaiMan** [comment]
type() only excepts characters found on a US-keyboard. (see docs)

try paste() instead.
