### ISSUE TITLE
Source code for 1.0.1

### ISSUE THREAD

**Issue by p-elsie** [RaiMan/SikuliX-2014#161]
I'm using 1.0.1.  Are the sources still available somewhere?

The class files in my sikuli-java.jar have file date 2013-09-12.  org.sikuli.script.Region decompiles to 1595 lines, but the original commit in SikuliX-2014 is 3403 lines.  

There was a repo at https://github.com/RaiMan/SikuliX-IDE and another at https://github.com/RaiMan/SikuliX-API but they're gone now.  They're still linked on https://launchpad.net/sikuli/sikulix/1.0.1

https://github.com/sikuli/sikuli seems to be for X-1.0rc3

**Comment by RaiMan** [comment]
Sorry, but the source code for 1.0.1 is not available.
You have to use it as is.

If you want to work with the sources too, you have to switch to version 1.1.0
