### ISSUE TITLE
Using Tesseract API to read numbers

### ISSUE THREAD

**Issue by immohuneke** [RaiMan/SikuliX-2014#174]
I am finding it very hard to read number strings using Region.text() as described in the documentation.

I found a test script [here](https://github.com/RaiMan/SikuliX-2014/blob/2633770651102b4772f7f0276b641795c17ebd23/StuffContainer/testScripts/testGrid/test1.sikuli/test1.py): check out lines 25-48. The full list of Tesseract 3.02 parameters is given [here](http://www.sk-spell.sk.cx/tesseract-ocr-parameters-in-302-version).

But no matter what I try to set the following parameters to, it seems to have no effect on the outcome - the string "21" is always correctly recognised as "21", whereas the string "13" comes out as "'|3" (that is, single-opening-quote, vertical bar, numeral three - where the vertical bar is by default the "unrecognised character" symbol). I have tried any number of combinations of these parameters:

* OCR.setParameter("classify_bln_numeric_mode", "T")
* OCR.setParameter("chs_leading_punct", "")
* OCR.setParameter("chs_trailing_punct1", "")
* OCR.setParameter("chs_trailing_punct2", "")
* OCR.setParameter("numeric_punctuation", "-,.")
* OCR.setParameter("unrecognised_char", "@")
* OCR.setParameter("tessedit_char_whitelist", "0123456789")
or
* OCR.setParameter("tessedit_char_whitelist", "0123456789-.")

I suspect therefore that in fact the setParameter call has no effect. Can this be verified somehow?

CORRECTION: if the setParameter call is made BEFORE the import of TR, it DOES appear to have the desired effect. My test program now reads:

Settings.OcrTextRead = True
Settings.OcrLanguage = "eng"
import org.sikuli.natives.OCR as OCR
OCR.setParameter("classify_bln_numeric_mode", "T")
OCR.setParameter("chs_leading_punct", "")
OCR.setParameter("chs_trailing_punct1", "")
OCR.setParameter("chs_trailing_punct2", "")
OCR.setParameter("numeric_punctuation", "-,.")
OCR.setParameter("unrecognised_char", "@")
OCR.setParameter("tessedit_char_whitelist", "0123456789")
import org.sikuli.script.TextRecognizer as TR
TR.getInstance()

etc.

**Comment by RaiMan** [comment]
Thanks for the evaluation.
You are partly right: The TextRecognizer must be newly instantiated, to hand over parameters to Tesseract, that where set using OCR.setParameter().

... but this is the recommended approach (valid for final 1.1.0):
```
Settings.OcrTextRead = True
Settings.OcrLanguage = "eng"
import org.sikuli.natives.OCR as OCR
import org.sikuli.script.TextRecognizer as TR

# now set the parameters for Tesseract
OCR.setParameter("classify_bln_numeric_mode", "T")
OCR.setParameter("chs_leading_punct", "")
OCR.setParameter("chs_trailing_punct1", "")
OCR.setParameter("chs_trailing_punct2", "")
OCR.setParameter("numeric_punctuation", "-,.")
OCR.setParameter("unrecognised_char", "@")
OCR.setParameter("tessedit_char_whitelist", "0123456789")

# now reset Tesseract, to force the re-instantiation at next usage of Region.text()
# which will then use the given parameters
TR.reset()

# now read some text
number = someImage.text()
```

I will put this to the docs.

**Comment by immohuneke** [comment]
This is not correct. I have tried just changing TR.getInstance() to TR.reset() and then numeric string recognition no longer works correctly. You may need both calls. I'm experimenting some more.

**Comment by RaiMan** [comment]
ok, after having tested again:
```OCR.setParameter()```
seems to be in effect simply for the next following Region.text() without any additional measures.

TR.reset() indeed does not have any additional effect for the Tesseract parameters.
I think it is only needed, if you want to change the language and/or the tessdata folder location.

This makes sense, because 
```TR.getInstance()```
simply does nothing, if TR is already instantiated (TR is a singleton class).

I have changed my above comment accordingly.

**Comment by RaiMan** [comment]
... and now I have found the secret behind TR.reset():
`TR.reset()`can be used to unset all parameters.
But to allow `OCR.setParameter()` to work at all, TR must be instantiated.

So this will reset the TextRecognizer and then accept `OCR.setParameter()` as expected:

```
Settings.OcrTextRead = True
Settings.OcrLanguage = "eng"
import org.sikuli.natives.OCR as OCR
import org.sikuli.script.TextRecognizer as TR

# reset the TextRecognizer
TR.reset()
# instantiate it 
TR.getInstance()
# this will work with an empty whitelist even on rerun in IDE
reg.text()

# switch OCR to numbers only
OCR.setParameter("tessedit_char_whitelist", "0123456789-.")
reg.text()
```
