### ISSUE TITLE
error Settings: load version file sikulixversion.txt did not work

### ISSUE THREAD

**Issue by andy-tom** [RaiMan/SikuliX-2014#176]
Hi, probably a simple solution, but I can't find it. Since I've moved to 1.1 (from 1.0.1), the script work will work in the IDE, but doesn't without. Here is debug lvl 3:

running SikuliX: -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine
-jar /home/andy/zzapps/sikuli11/sikulix.jar -d 3 -r z_Shift_Report.py
[debug] RunTimeINIT: lsb_release -i -r -s 
[debug] RunTimeINIT: loadOptions: check: /home/andy/z_Shift_Report.sikuli
[debug] RunTimeINIT: loadOptions: check: /home/andy
[debug] RunTimeINIT: loadOptions: check: /home/andy/.Sikulix/SikulixStore
[error] Settings: load version file sikulixversion.txt did not work
[error] ***** Terminating SikuliX after a fatal error 999 *****
It makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.
[debug] Sikulix: cleanUp: 0
[debug] Observing: as requested: removed all observers
[debug] RunTimeINIT: exists libs folder at: /home/andy/.Sikulix/SikulixLibs_
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:487)
	at org.sikuli.script.Sikulix.terminate(Sikulix.java:470)
	at org.sikuli.script.RunTime.initSikulixOptions(RunTime.java:1651)
	at org.sikuli.script.RunTime.get(RunTime.java:289)
	at org.sikuli.ide.SikuliIDE.run(SikuliIDE.java:177)
	at org.sikuli.ide.Sikulix.main(Sikulix.java:21)
Caused by: java.lang.NullPointerException
	at org.sikuli.script.RunTime.makeFolders(RunTime.java:779)
	at org.sikuli.script.RunTime.libsExport(RunTime.java:884)
	at org.sikuli.script.RunTime.libsLoad(RunTime.java:819)
	at org.sikuli.script.RunTime.loadLibrary(RunTime.java:982)
	at org.sikuli.script.Screen.<clinit>(Screen.java:57)
	... 6 more

**Comment by RaiMan** [comment]
Have a look at the setup log file: everything ok?

- looks like a not correctly assembled sikulix.jar
- debug level 3 is sufficient

**Comment by RaiMan** [comment]
Just accidentally got the same error:
It seems to happen when debug level is set to 4 using
-d 4

So use 
-d 3
and it should work.

**Comment by andy-tom** [comment]
Hey RaiMan, many thanks for your help.

I can't find anything that looks problematic in the setup log or -d 3 output. When you say not correctly assembled sikuli.jar, do you mean that I should re-download the setup file and start again?

I have tried a few scripts that I have made, and none of them seem to be running as far as I can tell.

I'll attach the setup log, and here is the -d 3 output:

running SikuliX: -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine
-jar /home/andy/zzapps/sikuli11/sikulix.jar -d 3 -r /home/andy/z_Shift_Report.sikuli/z_Shift_Report.py
[debug] RunTimeINIT: lsb_release -i -r -s 
[debug] RunTimeINIT: loadOptions: check: /home/andy
[debug] RunTimeINIT: loadOptions: check: /home/andy
[debug] RunTimeINIT: loadOptions: check: /home/andy/.Sikulix/SikulixStore
[debug] RunTimeINIT: global init: entering as: IDE
[debug] RunTimeINIT: ScreenDevice 0 has (0,0) --- will be primary Screen(0)
[debug] RunTimeINIT: Monitor 0: (0, 0) 1366 x 768
[debug] RunTimeINIT: runs as sikulix.jar in: /home/andy/zzapps/sikuli11
[debug] RunTimeINIT: exists libs folder at: /home/andy/.Sikulix/SikulixLibs_201510051707
***** show environment for IDE (build 201510051707)
user.home: /home/andy
user.dir (work dir): /home/andy
user.name: andy
java.io.tmpdir: /tmp
running 64Bit on Linux (0 Ubuntu 15.10) from a jar
java 7-64 version 1.7.0_91-b02 vm 24.91-b01 class 51.0 arch amd64
app data folder: /home/andy/.Sikulix
libs folder: /home/andy/.Sikulix/SikulixLibs_201510051707
executing jar: /home/andy/zzapps/sikuli11/sikulix.jar
*** classpath dump sikulix
  0: /home/andy/zzapps/sikuli11/sikulix.jar
*** classpath dump end
***** show environment end
[debug] RunTimeIDE: global init: leaving
[debug] RunTimeIDE: initIDEbefore: entering
[debug] RunTimeIDE: initIDEbefore: leaving
[debug] RunTimeIDE: initAPI: entering
[debug] RunTimeIDE: initAPI: leaving
[debug] init user preferences
[debug] IDE: running with Locale: en_US
[debug] IDE: Switching to ScriptRunner with option -r, -t or -i
[debug] Runner: commandline: -d 3 -r /home/andy/z_Shift_Report.sikuli/z_Shift_Report.py
[debug] --- Sikuli parameters ---
[debug] 1: -d
[debug] 2: 3
[debug] 3: -r
[debug] 4: /home/andy/z_Shift_Report.sikuli/z_Shift_Report.py
[debug] ScriptingSupport: givenScriptName:
/home/andy/z_Shift_Report.sikuli/z_Shift_Report.py
[debug] RunTimeIDE: final cleanup
[debug] FileManager: deleteFileOrFolder:
/tmp/Sikulix_850336602
[SikuliX-1.1.0-SetupLog.txt](https://github.com/RaiMan/SikuliX-2014/files/52816/SikuliX-1.1.0-SetupLog.txt)

**Comment by RaiMan** [comment]
Sorry, you seem to not have seen my above comment.

**Comment by andy-tom** [comment]
I think I did, I've tried with and without debug, and my scripts just seem to do nothing unless run through the IDE. Any help is useful.

**Comment by RaiMan** [comment]
just try this
-jar /home/andy/zzapps/sikuli11/sikulix.jar -d 3 -r /home/andy/z_Shift_Report.sikuli

**Comment by andy-tom** [comment]
All good. Thanks for your time. Hopefully I can contribute something back some time. I knew it would be something simple, it was as you point out just the way you specify the script has changed a little since 1.0.1.
