### ISSUE TITLE
Behaviour of type

### ISSUE THREAD

**Issue by MarkusSchadegg** [RaiMan/SikuliX-2014#177]
Hi,

just debugged... and debugged... and debugged my pyhton script... and then I found out, that I should not code 

    type("http://www.google.de")

but I should code:

    type("http")
    type(".", Key.SHIFT)
    type("7", Key.SHIFT)
    type("7", Key.SHIFT)
    type("google.de")

I understand this, because when you fill that into a keyboard driver, it will be correct like this...

What about a convinience method like typeText(), where you replace all characters, that are not possible to type directly(":", "/" and so on...) you already seem to do this for uppercase keys, that should - following the keyboard logic - be typed with Key.SHIFT also:

    type("Hello") # works!!
    type("h", Key.SHIFT); type("ello") # works also...

Greetings,

Markus

**Comment by RaiMan** [comment]
This is a well known and documented behavior since beginning.
see https://answers.launchpad.net/sikuli/+faq/933

In your case, you simply should have used paste() instead of type()

Nevertheless it is on the list for version 2, to enhance the type() feature (as feature write() )

**Comment by MarkusSchadegg** [comment]
My reason is: 
my tested application often uses clipboard functionality... testing this app with sikulix becomes complicated then

**Comment by RaiMan** [comment]
Sorry for that, but with current version 1.1.0 the mentioned solutions are the only that are available.
Possible improvements will only get available during the next months with pre-versions of version 2.

You might try to make your own experiences with the Java Robot class or other Java based solutions, that might be available in the net.
If you do that and have questions, then you are welcome, to come back.
