### ISSUE TITLE
SikuliX java linux setup

### ISSUE THREAD

**Issue by vyawharevijay** [RaiMan/SikuliX-2014#192]
sikulix api is not working in ubuntu

[info] runcmd: lsb_release -i -r -s 
[error] Can't initialize global Robot for Mouse: headless environment
[error] ***** Terminating SikuliX after a fatal error 999 *****
It makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sikuli.testsikuli.TestNew.main(TestNew.java:10)
Caused by: java.lang.NullPointerException
	at org.sikuli.script.Screen.getPrimaryScreen(Screen.java:337)
	at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:487)
	at org.sikuli.script.Sikulix.terminate(Sikulix.java:470)
	at org.sikuli.script.Screen.getMouseRobot(Screen.java:120)
	at org.sikuli.script.Screen.initScreens(Screen.java:76)
	at org.sikuli.script.Screen.<clinit>(Screen.java:58)
	... 1 more

**Comment by RaiMan** [comment]
[error] Can't initialize global Robot for Mouse: headless environment

do you really run in a headless environment?
NOT possible !!!

**Comment by vyawharevijay** [comment]
its working after passing jvm argumnet java.awt.headless=false

**Comment by RaiMan** [comment]
That might be, but you might run into other problems, when using SikuliX features, that need a real screen attached.

**Comment by vyawharevijay** [comment]
I m nt facing any issue as of now,my code with sikuli-script.jar is working fine.

**Comment by RaiMan** [comment]
thanks for the confirmation. all the best,

**Comment by dsharma1** [comment]
Hi,vyawharevijay Where and how did u set  jvm argumnet java.awt.headless=false? I am getting the same issue, but I am not sure where to put the jvm args? It is passed as a parameter of mvn  while you are running your tests?

**Comment by rodel-talampas** [comment]
@dsharma1  just do a java -Djava.awt.headless=false XXXXX  if you are using Java

**Comment by njchandu** [comment]
Facing similar issue when running it via Jenkins. I added the -Djava.awt.headless=false argument, while starting the selenium server.
