### ISSUE TITLE
Connect to VNC via IDE

### ISSUE THREAD

**Issue by jivank** [RaiMan/SikuliX-2014#193]
I am trying to run a VNC connection via the IDE.

> from java.net import Socket
from edu.unh.iol.dlc import VNCScreen
from edu.unh.iol.dlc import ConnectionController
s = Socket("192.168.99.100", 5900)
s.setSoTimeout(1000)
s.setKeepAlive(true)
cc = ConnectionController(s)
cc.setPixelFormat(0, "Truecolor", 32, 0)
cc.start(0)
sleep(2)
vnc = VNCScreen()
vnc.type('hello')

I get this error:

> [error] Did not find any active ConnectionControllers.  Cannot use VNCScreen without a ConnectionController instance.

Any ideas?

**Comment by jivank** [comment]
>from java.net import Socket
from edu.unh.iol.dlc import ConnectionController

>s = Socket("192.168.99.100", 5900)
s.setSoTimeout(10000)
s.setKeepAlive(True)
cc = ConnectionController([s])
cc.openConnection(0)
cc.start(0)
sleep(2)

>from edu.unh.iol.dlc import VNCScreen
vnc = VNCScreen(0)
vnc.type('hello')
cc.closeConnection(0)

This seems to work. A cool feature for SikuliX2 would be to be able to choose VNC hosts or choose the local machine to execute the Sikuli script.

**Comment by RaiMan** [comment]
> A cool feature for SikuliX2


... you will get it ;-)
