### ISSUE TITLE
Fatal error if list is passed in doFind

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#200]
There is an error in my script when a list with single image is passed to `exists()` function. But SikuliX 1.1.1 doesn't report it and just exits silently.
```
...
[info] IDE startup: 27.9 seconds
[debug] IDE startup: 27.9 seconds
[debug] Jython: requested to use as default region: R[0,0 1280x800]@S(0)
[debug] JythonScriptRunner: runPython: running script from IDE:
E:/_IDE_/SikuliX-111/Rstrip.sikuli
[debug] Region: exists: waiting 3.0 secs for ['hire.png'] to appear in R[0,0 1280x800]@S(0)
[error] Region: doFind: invalid parameter: ['hire.png']
[error] ***** Terminating SikuliX after a fatal error 999 *****
It makes no sense to continue!
If you do not have any idea about the error cause or solution, run again
with a Debug level of 3. You might paste the output to the Q&A board.
[debug] Sikulix: cleanUp: 0
[debug] RunTimeIDE: final cleanup
[debug] FileManager: deleteFileOrFolder:
C:\Users\user\AppData\Local\Temp2\Sikulix_1142353438
```

**Comment by RaiMan** [comment]
passing lists of images to exists() is not defined and not checked at the API level.

... but the error message should be enough for now:
[error] Region: doFind: invalid parameter: ['hire.png']

in version 2, I will do it better ;-)

**Comment by techtonik** [comment]
@RaiMan is it possible to check it (or add as a feature to check multiple images at once)? There is a feeling that we've discussed this earlier, didn't we?

**Comment by techtonik** [comment]
I mean it really takes a lot of time to debug this error. This error is not shown in IDE pane - SikuliX crashes and the error is shown in Windows console and only if debug flag is specified.

**Comment by RaiMan** [comment]
-- I mean it really takes a lot of time to debug this error.
ok, understood and agreed: SikuliX should not silently crash, but show some reasonable error behavior.
I will fix it in 1.1.1

-- feature to check multiple images at once
This feature will completely be available only in version 2.
Currently there is an experimental base implementation, to search for multiple targets in parallel (faster only with more than 3 targets compared to a serious of exists).
Region.findBest(img1, img2, img3, ...)
and returns the match with the highest score.
If you urgently need such a feature with 1.1.x at the scripting level, then I recommend, to implement your own threaded solution, that can handle a bunch of targets in parallel using exists(img, 0)

**Comment by techtonik** [comment]
> ok, understood and agreed: SikuliX should not silently crash, but show some reasonable error behavior.
> I will fix it in 1.1.1

THanks. =)

> Currently there is an experimental base implementation, to search for multiple targets in parallel 

I also think that SikuliX needs API to reach for external services (like neural network service) for that task, although it seems that Python can already make this possible. Only picture object needs to be serialized somehow.

**Comment by RaiMan** [comment]
> API to reach for external services (like neural network service)
Do you have an example for me of such a service.
Supposing it is used by issuing some RESTful http requests: I added a feature in 1.1.1, to issue http requests based on Apache org.apache.httpcomponents.httpclient.
The API will be in App class.

**Comment by techtonik** [comment]
No unified or public API that I dealt with, but http://demo.caffe.berkeleyvision.org/ is the showcase of technology that could be exposed.

**Comment by techtonik** [comment]
Issuing requests is not a problem for Python. The problem is how to pass image data for matching.

**Comment by RaiMan** [comment]
> Issuing requests is not a problem for Python. 

I know of course ;-)
You might implement the complete SikuliX in Python - no problem at all.

But with SikuliX features I have to think at the Java level due to history and intended availability.

**Comment by RaiMan** [comment]
> but http://demo.caffe.berkeleyvision.org/ is the showcase of technology that could be exposed.

ok, understood and interesting.

... but this currently is surely not one of my priorities.

Version 2 will have easier possibilities to add "plugins". So something like this might be a candidate.
