### ISSUE TITLE
Idea/enhancement: code folding?

### ISSUE THREAD

**Issue by grayma** [RaiMan/SikuliX-2014#204]
I didn't see this anywhere, in preferences or on the git (might not have looked perfectly far though), but what are the possibilities of code folding?  I feel like it'd be a great help keeping code organized to the eye.  If it seems like a good idea I might try and contribute it, never made an open source contribution but I'd love to give it a shot if it seems doable.

**Comment by RaiMan** [comment]
Talking about SikuliX IDE?

not planned to do anything in this direction.

Version 2 will use JEdit as bundled scripteditor, that has all these features.

If you need such aspects, you should use real IDE's like Eclipse and PyCharm. In parallel you can stick with the SikuliX IDE to manage your images.
