### ISSUE TITLE
Take over the sikulix package on Chocolatey.org

### ISSUE THREAD

**Issue by AnthonyMastrean** [RaiMan/SikuliX-2014#209]
Packages owned and published by the application developers can benefit from "trusted" package status, which allows you to skip manual moderation. That means your application is published and available faster and with less fuss.

I'm a package moderator and can help transition ownership and get you trusted package status.

FYI, I'm giving up on maintaining this package. If you're not interested, there's only 1 other community member [offering to help](https://twitter.com/jessesanford/status/743498075054940160).

https://chocolatey.org/packages/sikulix

**Comment by RaiMan** [comment]
May be I am dreaming, but I thought, that I already signaled to be happy to take over (see Twitter).

**Comment by AnthonyMastrean** [comment]
You probably did and I lost track :)

So much has changed in Chocolatey internals since the early versions, I was happy to make an update. I have an idea on how to hand this package over (short version: I'll move the package to a new repo and you can clone or move it to your user account) and what documentation you'll need.

I'll comment here when that's done.

**Comment by AnthonyMastrean** [comment]
Alright, I prepared a standalone repository for just the sikulix package. I transferred ownership (it's pending). When the next version is published, you can update the package (change the version, some of the URLs, etc.).

I'll review, I can moderate the package, and we can get the trusted status setup.

**Comment by RaiMan** [comment]
???
Where do I have to look?

**Comment by AnthonyMastrean** [comment]
I don't know... I've never transferred a repository before! Try looking in your profile notifications.

![image](https://cloud.githubusercontent.com/assets/217842/16206794/017a7868-36f8-11e6-9e1b-00fec5ba6866.png)

**Comment by RaiMan** [comment]
ok, now I understand, what you did.
... but I cannot find any notification, that allows me to take over.

**Comment by RaiMan** [comment]
as a fallback:
I have downloaded the zip of the repo, so I can setup my own from that.

So if it is not possible/suitable for you to recover the transfer, just purge the repo.
I wait for your decision.

**Comment by RaiMan** [comment]
I think I am now able to fly on my own:
https://github.com/RaiMan/SikuliX1-Chocolaty

I will give you a note, when I need some help.
thanks for now.

**Comment by AnthonyMastrean** [comment]
You're now the sole maintainer!

**Comment by shaworth** [comment]
Thank you both for your time and efforts.  Both are much appreciated.

**Comment by RaiMan** [comment]
@AnthonyMastrean 
... also thanks for you efforts.
seems to be a chance for me, to learn more about using Powershell ;-)
