### ISSUE TITLE
Windows 7 offline installation fails on a UNC path

### ISSUE THREAD

**Issue by moogleberry** [RaiMan/SikuliX-2014#212]
Installing SikuliX 1.1.0 in offline mode where files are stored at a UNC path results in the following situation:

The Installer copies the `sikulixlibswin-1.1.0.jar` file from the Downloads directory to the installation home directory.  The installer then errors saying it cannot find the file `sikulixlibswin.jar` even though the file is present.  UNC path shown in the error is prefixed with only one \ instead of two, which may be causing the file not found error when accessing the copied file.  

Copying all files to the C drive and running in the same way caused no errors and was successful.

**Comment by RaiMan** [comment]
UNC path something like this?
\\server-access-token\folder\folder ...

**Comment by moogleberry** [comment]
Yes, when i used something like that it broke the windows offline install.

**Comment by RaiMan** [comment]
I just looked into the code and decided to not fix this in version 1.1.x
As a workaround you have to assign a drive letter.

I have it on the list now for version 2, to generally support this kind of file path specification too.
