### ISSUE TITLE
Visual testing

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#213]
Hi RaiMain.

Gratz with getting 1.1.1 out of the door soon.

Do you have any tutorial for people on the web on how to setup SikuliX for automated testing? [This doc](http://sikulix-2014.readthedocs.io/en/latest/basicinfo.html?highlight=testing#sikulix-can-be-used-for-visual-testing) mentions it, but, apparently, it is not enough.

**Comment by RaiMan** [comment]
Sorry, no. The only framework, I will have a little more specific docs in the future is for RobotFramework and later about Selenium, since I want to support both better out of the box.

You have to consult the web.

**Comment by techtonik** [comment]
Running visual tests are not hard, and I remember there specific support in Sikuli about it. Was it stripped out?

**Comment by RaiMan** [comment]
If you are talking about the test cases feature in the IDE: yes, purged, since it was only some toy, that could not satisfy people in most aspects. It was a very specific implementation and hard to enrich with new features.
see: https://answers.launchpad.net/sikuli/+faq/1804
