### ISSUE TITLE
Could not load JIntellitype.dll when launching "runsikulix.cmd"

### ISSUE THREAD

**Issue by BornLuna** [RaiMan/SikuliX-2014#214]
Whenever I try and run the program using `runsikulix.cmd` I get the following error, an then the cmd closes

```+++ running this Java
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)
+++ trying to run SikuliX
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar C:\MapleBot\sikulix.jar
[info] HotkeyManager: add Capture Hotkey: CTRL+SHIFT 2 (50, 3)
[error] WindowsHotkeyManager: JIntellitype problem: Could not load JIntellitype.dll from local file system or from inside JAR```

**Comment by RaiMan** [comment]
which versions? SikuliX, Windows
run with option -d 3 and look into the degug output.

**Comment by BornLuna** [comment]
Ended up fixing it

**Comment by RezzZ** [comment]
thanks for sharing your solution? .. Got the same problem since a reboot this morning because of some system updates.

[sikulix.txt](https://github.com/RaiMan/SikuliX-2014/files/344444/sikulix.txt)

runing windows 10x64
SikuliX-1.1.0

**Comment by RaiMan** [comment]
@brandy 
I would also be interested in your fix solution. thanks

**Comment by RezzZ** [comment]
I just installed the nightly build for 1.1.1. That one works for now :).

**Comment by RezzZ** [comment]
and it suddenly stopped working again... nothing installed on my system in the meantime...

**Comment by AshishLS** [comment]
I was getting the same error on my Win 10 64 bit laptop.
After spending few hours trying things suggested here and on other blogs, I installed latest version of Java (8). This installation prompted me to remove other older versions at the end of setup. 
Now SikuliX IDE is working.

**Comment by CarolCiola** [comment]
Got the same issue on Win7 64 bits. At starting Sikuli, the command window shows this message and closes Sikuli automatically.

**Comment by RaiMan** [comment]
@CarolCiola 
Supposing it is version 1.1.1 (http://sikulix.com)
As mentioned above: check your Java installation and environment/path settings. In doubt remove all existing Javas and install only one 64-bit version.

**Comment by CarolCiola** [comment]
@RaiMan 
Got the latest Java version but wasn't sufficient. Had to download JIntellitype.dll on https://github.com/melloware/jintellitype and paste it on C:\Windows\System32.

Sikuli 1.1.1. is now OK.
[]s

**Comment by RaiMan** [comment]
@CarolCiola 
ok, thanks for coming back with your information.
I will check wether the bundled stuff is different and fix it.

**Comment by ogchavez** [comment]
If anybody else is still dealing with this, what helped me was to install the JDK along with the JRE. 
Using :  
Java 1.8.xx
jdk1.8.0_144
Windows 10 64

**Comment by Easy-B** [comment]
Still reproduses sometimes

**Comment by Easy-B** [comment]
Still reproduses sometimes
Sikuli 1.1.1.

**Comment by Easy-B** [comment]
Still reproduses sometimes
Sikuli 1.1.1.
OS Name:                   Windows 10 Pro 
OS Version:                10.0.16299 Build 16299
Jawa (build 1.8.0_161-b12)

Workaround: restart PC
