### ISSUE TITLE
Download of selenium4sikulix.jar fails during setup

### ISSUE THREAD

**Issue by UnitedMarsupials** [RaiMan/SikuliX-2014#217]
I'm trying to build an RPM for local consumption here. The setup-stage is invoked thus:
```
java -Duser.home=/tmp/buildroot/usr/share/sikuli -jar Setup/target/sikulixsetup-1.1.0-forsetup.jar options 1.3 2 3 4.3 buildv ext not
```
It fails with:
```
[debug (6/29/16 3:15:45 PM)] FileManager: Downloading selenium4sikulix.jar with unknown size
[error (6/29/16 3:15:45 PM)] FileManager: problems while downloading
java.io.FileNotFoundException: https://launchpad.net/raiman/sikulix2013+/1.1.0/+download/selenium4sikulix.jar
```
Indeed, the link responds with a 404... Please, fix the problem and advise of a work-around.

Meanwhile, what is the feature the `selenium4sikulix.jar` enables? Just in case we don't need it, is there a way to disable it? Thanks!

**Comment by UnitedMarsupials** [comment]
Actually, it looks like the source for it comes with Sikuli: `StuffContainer/Extensions/Selenium4Sikulix/src/main/java/org/sikuli/selenium4sikulix/Sikuilix.java`. So, why is it not compiled on the spot, but downloaded (from incorrect location) instead?

**Comment by UnitedMarsupials** [comment]
> do not use the option ext

Thanks, I figured this much by now :) But that brings another point -- does my selecting the options at setup-time (whether through the GUI or through the command-line) merely provides for the necessary files' download, or does it somehow else "enable" them?

That is, say I do not include JRuby and Jython at setup-time... Can I still use them later by explicitly including their respective JARs on Java command-line? Something like:
````sh
java -cp /usr/share/java/jruby.jar:${SIKULIX_HOME}/sikulix.jar org.sikuli.ide.Sikulix
````
Or is it too late by then because something buried inside `sikulix.jar` already says "jRuby = false"?

Also, whatever options I tried with setup, the `sikulixapi.jar` is buried inside `sikulix.jar`. Given that the former is much smaller and may be useable directly (via `org.sikuli.script.Sikulix`), would not it make sense to keep the two separate? So that the use-cases, where only the smaller API JAR is needed, could use the smaller JAR?

Am I wrong and the `sikulixapi.jar` is not actually useful for anything by itself? If it is, how do I prevent it from being included into `sikulix.jar`?

**Comment by RaiMan** [comment]
--- sikulix.jar (SikuliX IDE)
depending on setup either Jython or JRuby or both are bundled with the jar.
It is intended, to run scripts from within the IDE or from commandline.
The target group are scripters with low to medium programming skills and low demand on professional ecosystems.
It should never be used with an external Jython or JRuby and it does not make sense anyways.

--- sikulixapi.jar (SikuliX Java API)
the heart of SikuliX, where the features are implemented. Hence it MUST be contained in the IDE jar.
If you want to use SikuliX features in a Java aware scripting environment (Jython, JRuby, Scala, Groovy, Clojure, ...) with your own setup, you need a valid sikulixapi.jar, that has to be appropriately setup in your environment (classpath, import, ...). 

typical professional usages for P(J)ython scripting
- Jython installation
- Eclipse with PyDev or PyCharm

For the other Java aware scripting situations there are similar setups depending on the used IDE.

**Comment by RaiMan** [comment]
... comment on your setup options used (supposing setup runs on Linux/Unix):
this is appropriate if you want to setup your own scripting environment (according to the comment before):
options 2 3 buildv not
... which would finally result in a working sikulixapi.jar

**Comment by UnitedMarsupials** [comment]
> It should never be used with an external Jython or JRuby and it does not make sense anyways.

Why would not it make sense to use an external jruby.jar, for example?

> sikulixapi.jar is the heart of SikuliX, where the features are implemented. Hence it MUST be contained in the IDE jar.

Sorry, I don't see, how one follows from the other. Yes, `sikulixapi.jar` must be known to Java VM for Sikuli to run, but that does not mean, it has to be inside the same jar. One can run, for example:

    java -cp /some/where/JXGrabKey.jar:/else/where/jruby.jar:/opt/sikuli/sikulixapi.jar:/opt/sikuli/sikulixide.jar org.sikuli.ide.Sikulix

why do you insist on sticking all of the components (required and optional alike) into `sikulix.jar`? It may be _neater_ to bundle them all into one file, but, if some of the components may be usable separately (jruby.jar certainly may be, for example), such bundling causes the user's machine to waste memory for no good reason...

**Comment by toschneck** [comment]
Just FYI, we implement something similar on top of Sikuli and Sahi (similar web test framework as Selenium), maybe take a look at https://github.com/ConSol/sakuli

**Comment by RaiMan** [comment]
@UnitedMarsupials 

> Why would not it make sense to use an external jruby.jar, for example?

This was meant with respect to sikulix.jar: a package to be ready to use for non-programmers to edit and run more or less complex scripts with an IDE, which usually does not fulfill the requirements of a professional.

Feel free, to do whatever you want with the building blocks of SikuliX (packaged or not).
Just run a Maven "clean install" at the project root and assemble your own packages or use the "naked" jars as you like.

I admit, that the support for linux/unix systems is poor, which is the the base for your problems.
If the packages created by setup would have run out of the box on your system, you would not have had anything to complain.

**Comment by RaiMan** [comment]
@toschneck 
Congratulations - looks good :-)
I would highly appreciate if you change the link for Sikuli(X) in your Readme to
http://sikulix.com, since you seem to be based on the latest SikuliX (1.1.x).
all the best.

**Comment by toschneck** [comment]
@RaiMan thx! Sure, I will fix it quickly! Thank you for your great work with sikulix, for your usecases it is more then fantastic!

**Comment by UnitedMarsupials** [comment]
> Just run a Maven "clean install" at the project root and assemble your own packages or use the "naked" jars as you like.

Ok, thanks for the pointer... I was worried, the bundling process makes some other changes inside the resulting JAR -- like setting "`jRuby = false`" somewhere. If the availability of features is determined purely by the availability of relevant JARs at run-time, then, yes, I can do whatever I want to.

> I admit, that the support for linux/unix systems is poor

There is nothing to admit -- you are an application programmer, stick to Sikuli. The OS-specific packagers like myself will take care of OS, well, OS-specific packaging.

> If the packages created by setup would have run out of the box on your system

I, probably, would have found something _anyway_ :-) Thanks!
