### ISSUE TITLE
Sikuli can not test itself

### ISSUE THREAD

**Issue by UnitedMarsupials** [RaiMan/SikuliX-2014#221]
I'm porting SikuliX to CentOS-7 (for my employer) and FreeBSD (for my own pleasure) and got it to build and run after some serious modifications (patches available upon request).

However, I can not reliably test the results because SikuliX _does not have a self-test suit_. What little there is under `TestScripts/` is hardly comprehensive and is mostly broken anyway.

Wouldn't it be great, if a GUI application designed to test GUI applications were able to _test itself_? And it can -- it is just that no such tests have been created or, at least, none that are bundled with the application's source code...

In my opinion, this deficiency is hampering the development efforts -- unless the developers actually do have such a test-suit, but simply aren't sharing it... How do you fix a bug or add a feature without being able to _automatically_ confirm, that the change has not accidentally broken something else?

I'd say, creating such a suit should have a very high priority...

**Comment by RaiMan** [comment]
Currently a [regression test suite](https://github.com/RaiMan/sikuli-regression-tests) is under development, which besides helping testing after bug fixing in version 1.1.x will also be the base for making sure, that version 2 will be backwards compatible.

Version 2 will have basic function tests available from the beginning.

**Comment by UnitedMarsupials** [comment]
Is the current test suit already usable -- even if it does not offer _full_ coverage? (If such _full_ coverage is even possible in principle, that is.)

Even if it provides merely a "smoke test" at this time, it is much better than nothing at all. How would I use it?

**Comment by RaiMan** [comment]
https://github.com/RaiMan/sikuli-regression-tests

I added a ReadMe.
