### ISSUE TITLE
App.open does not work on Mac for Adobe Photoshop

### ISSUE THREAD

**Issue by nicolasavenza** [RaiMan/SikuliX-2014#229]
Using the Java API, I'm not able to open Photoshop using the following:

```
String target = "Adobe Photoshop CS6"
app = new App(target);
App result = app.open(Integer.MAX_VALUE);

[error] App.open failed: "Adobe Photoshop CS6" not found
```

I've also tried entering the full path to the application folder but it still does not work. Eg:

```
target = "/Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app"
target = "/Applications/Adobe Photoshop CS6/" 
```

Neither of which work.

Currently I'm having to use a CL script as a workaround: open -a "Adobe Photoshop CS6"

However this does not allow me to continue using the App object and all the conveniences it provides.

**Comment by RaiMan** [comment]
App.open on Mac currently apparently only works, if the app-name.app is stored at the root level of /Applications.
... and only app-name can then be used 

... but even this does not work in all cases (for me IntelliJ IDEA CE.app does not work e.g.)

So I am afraid, that it will not work for you.

If you are familiar with AppleScript, you might run AS-snippets inline in your script this way:

an = "IntelliJ IDEA CE"
cmd = """
applescript
tell application "%s" to activate
"""
cmd = cmd % an
returnCode = runScript(cmd)

... which would open the given app or bring it to front if it is already running.

Then you might use App.focusedWindow(), to get the region of the app's frontmost window.

**Comment by nicolasavenza** [comment]
Thanks RaiMan, I'll give that a try.
