### ISSUE TITLE
terminating: JythonScriptRunner: cannot be initialized: Cannot create PyString with non-byte value

### ISSUE THREAD

**Issue by liujb0319** [RaiMan/SikuliX-2014#230]
hi,

I am trying to produce the ready_to_use jar packages, but ended up with the following error.

## **1.    mvn clean install**

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sikulix1 ........................................... SUCCESS [  0.305 s]
[INFO] sikulixlibslux ..................................... SUCCESS [  2.089 s]
[INFO] sikulixlibsmac ..................................... SUCCESS [  1.631 s]
[INFO] sikulixlibswin ..................................... SUCCESS [  3.665 s]
[INFO] sikulixapi ......................................... SUCCESS [  7.810 s]
[INFO] sikulixsetupAPI .................................... SUCCESS [  6.762 s]
[INFO] sxjygments ......................................... SUCCESS [  0.676 s]
[INFO] sikulix ............................................ SUCCESS [ 14.908 s]
[INFO] sikulixsetupIDE .................................... SUCCESS [  6.771 s]
[INFO] sikulixsetup ....................................... SUCCESS [  6.176 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.965 s
[INFO] Finished at: 2016-10-21T14:18:15+08:00
[INFO] Final Memory: 29M/197M
[INFO] ------------------------------------------------------------------------

**## 2.   mvn -pl Setup exec:exec**

[debug (16-10-21 14:28:29)] RunSetup: processing commandfiles
[debug (16-10-21 14:28:29)] RunTimeSETUP: addToClasspath:
file:/C:/Users/liujb/AppData/Roaming/Sikulix/SikulixSetup/sikulix.jar
[debug (16-10-21 14:28:29)] RunTimeSETUP: exists libs folder at: C:\Users\liujb
AppData\Roaming\Sikulix\SikulixLibs_201610210617
[debug (16-10-21 14:28:29)] RunSetup: Jython: Trying to run functional test: ru
ning script statements via SikuliScript
[debug (16-10-21 14:28:34)] ScriptingSupport: initScriptingSupport: enter
**[error (16-10-21 14:28:35)] RunTimeSETUP:  *** terminating: JythonScriptRunner:
cannot be initialized:
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value**
[debug (16-10-21 14:28:35)] RunTimeSETUP: final cleanup
[debug (16-10-21 14:28:35)] FileManager: deleteFileOrFolder:
C:\Users\liujb\AppData\Local\Temp\Sikulix_172573096
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:22 min
[INFO] Finished at: 2016-10-21T14:28:36+08:00

D:\SikuliX-2014-master>java -version
java version "1.7.0_13"
Java(TM) SE Runtime Environment (build 1.7.0_13-b20)
Java HotSpot(TM) Client VM (build 23.7-b01, mixed mode, sharing)

downloaded the jar file a week ago from https://github.com/RaiMan/SikuliX-2014 

Can you please help me

**Comment by RaiMan** [comment]
If you did not do any changes in the sources, then you should go to the [nightly build page](http://nightly.sikuli.de).

Otherwise I need the complete setup log-file, to see what happens 
(mail to sikulix--at--outlook--dot--com)

I will check later today, what might go wrong.

**Comment by liujb0319** [comment]
The problem has been solved
I download the jar from nightly build page,and complete success.
Thanks very much,
