### ISSUE TITLE
FindFailedHandlers not available with Java?

### ISSUE THREAD

**Issue by cschlisner** [RaiMan/SikuliX-2014#233]
I have been trying to register a default findfailedhandler in Java, as it says it is possible (or at least used to be possible) on the wiki [here](http://sikulix-2014.readthedocs.io/en/latest/region.html?highlight=onFindFailed#findfailedhandler), but I've found that that code doesn't work at all. In fact, the only way to use the setFindFailedHandler() functions in either the Region class or the FindFailed class is if you do it with python or ruby. 

[Here's the code that would create a handler in FindFailed.java](https://github.com/RaiMan/SikuliX-2014/blob/master/API/src/main/java/org/sikuli/script/FindFailed.java#L81-L83)

Is there a reason for this restriction? I feel like the callback method would work fine with java.

**Comment by RaiMan** [comment]
in the docs (what you name wiki above) there is a note on java usage, which should work.
A given observer callback is only reassigned in case the call is coming from Jython or Ruby.
But anyways: the code snippet you mention above is not relevant, since the feature is implemented in class Region.

**Comment by cschlisner** [comment]
The example code does not work, because when you initialize a ObserverCallback Object with the default constructor, the Type property is left as Type.GENERIC (seen [here](https://github.com/RaiMan/SikuliX-2014/blob/master/API/src/main/java/org/sikuli/script/ObserverCallBack.java#L40-L41)), so when the Region class tries to call the Handler and checks for a Type.FINDFAILED property (seen [here](https://github.com/RaiMan/SikuliX-2014/blob/master/API/src/main/java/org/sikuli/script/Region.java#L2184-L2185)), the given Observer won't match and then the handler will never be called.

**Comment by cschlisner** [comment]
@RaiMan 
I have managed to get a handler working through Java with this code: 

```Java
Region.setFindFailedHandler(new ObserverCallBack(new Object(), ObserveEvent.Type.FINDFAILED) {
    @Override
     public void findfailed(ObserveEvent e) {
         // handling code
     }
});
``` 

The non-working example code on the website should be replaced with this or something else that actually works. 

Best wishes

**Comment by RaiMan** [comment]
@cschlisner 
thanks for not giving up and finding a solution (which needs ugly redundancies), that finally convinced me of having to do some revision of code and docs ;-)
Now it is possible to simply use `new ObserveCallBack()` and override the respective method, as [mentioned in the docs](http://sikulix-2014.readthedocs.io/en/latest/region.html#findfailedhandler).

On top I now mention in the docs the possibility to define global handlers for all newly created regions .
