### ISSUE TITLE
Install failed on ubuntu: libVisionProxy.so error

### ISSUE THREAD

**Issue by gbersac** [RaiMan/SikuliX-2014#235]
Thanks for this tool which seems amazing, but I can't install it. I am on ubuntu, and when launch this command line :

```bash
sudo java -jar sikulixsetup-1.1.0.jar
```

I get the following error log : [SikuliX-1.1.0-SetupLog.txt](https://github.com/RaiMan/SikuliX-2014/files/574075/SikuliX-1.1.0-SetupLog.txt)

**Comment by gbersac** [comment]
Ok, this was an easy one. I had to run the following command :

```bash
sudo apt-get install tesseract-ocr
```

And later for running functionnal tests :
```bash
sudo apt-get install wmctrl
sudo apt-get install xdotool
```
It was easy, but it would be even better if it was installed automatically or if would have been wrote in the documentation !

**Comment by RaiMan** [comment]
Fine, that you did it on your own.

> if would have been wrote in the documentation !

here you get the hint, that something special is on Linux:
http://www.sikulix.com/quickstart/#qs3

... and later this link:
http://www.sikulix.com/specials/files/linux-setup-prerequisites.html
