### ISSUE TITLE
Could not find com.github.vidstige:jadb:v1.0.

### ISSUE THREAD

**Issue by Prakash-Saravanan** [RaiMan/SikuliX-2014#236]
Update the dependency for the same https://github.com/vidstige/jadb/issues/14

**Comment by RaiMan** [comment]
this still works:
    <dependency>
      <groupId>com.github.vidstige</groupId>
      <artifactId>jadb</artifactId>
      <version>-v1.0-g94ebf38-23</version>
    </dependency>

**Comment by Prakash-Saravanan** [comment]
Facing the following error when using gradle

> Could not find com.github.vidstige:jadb:-v1.0-g94ebf38-23.
  Searched in the following locations:
      file:/C:/Users/prakash.saravanan/.m2/repository/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.pom
      file:/C:/Users/prakash.saravanan/.m2/repository/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.jar
      https://repo1.maven.org/maven2/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.pom
      https://repo1.maven.org/maven2/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.jar
      http://oss.sonatype.org/content/groups/public/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.pom
      http://oss.sonatype.org/content/groups/public/com/github/vidstige/jadb/-v1.0-g94ebf38-23/jadb--v1.0-g94ebf38-23.jar
  Required by:
      project : > com.sikulix:sikulixapi:1.1.1-SNAPSHOT
> Could not resolve com.sikulix:${sikulix.libs}:1.1.1-SNAPSHOT.
  Required by:
      project : > com.sikulix:sikulixapi:1.1.1-SNAPSHOT
   > Could not resolve com.sikulix:${sikulix.libs}:1.1.1-SNAPSHOT.
      > Unable to load Maven meta-data from http://oss.sonatype.org/content/groups/public/com/sikulix/$%7Bsikulix.libs%7D/1.1.1-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'http://oss.sonatype.org/content/groups/public/com/sikulix/$%7Bsikulix.libs%7D/1.1.1-SNAPSHOT/maven-metadata.xml'.
            > org.apache.http.client.ClientProtocolException (no error message)

**Comment by Prakash-Saravanan** [comment]
After adding `mave {url "https://jitpack.io"}` to build.gradle file, facing the following error

> Could not resolve com.github.vidstige:jadb:-v1.0-g94ebf38-23.
  Required by:
      project : > com.sikulix:sikulixapi:1.1.1-SNAPSHOT
   > Could not resolve com.github.vidstige:jadb:-v1.0-g94ebf38-23.
      > inconsistent module metadata found. Descriptor: com.github.vidstige:jadb:-SNAPSHOT Errors: bad version: expected='-v1.0-g94ebf38-23' found='-SNAPSHOT'
> Could not find com.sikulix:${sikulix.libs}:1.1.1-SNAPSHOT.
  Searched in the following locations:
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
  Required by:
      project : > com.sikulix:sikulixapi:1.1.1-SNAPSHOT

**Comment by Prakash-Saravanan** [comment]
After adding maven {url ""} and compile (''), facing the following error

> Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find com.sikulix:${sikulix.libs}:1.1.1-SNAPSHOT.
  Searched in the following locations:
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      file:/C:/Users/prakash.saravanan/.m2/repository/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
      https://devops-tools.pearson.com/nexus-deps/content/groups/all-deps/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      https://devops-tools.pearson.com/nexus-deps/content/groups/all-deps/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      https://devops-tools.pearson.com/nexus-deps/content/groups/all-deps/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/maven-metadata.xml
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.pom
      https://jitpack.io/com/sikulix/${sikulix.libs}/1.1.1-SNAPSHOT/${sikulix.libs}-1.1.1-SNAPSHOT.jar
  Required by:
      project : > com.sikulix:sikulixapi:1.1.1-SNAPSHOT

>

**Comment by RaiMan** [comment]
- That the current SikuliX POM does not work with Gradle is a known problem and will only be fixed in version 2

- the correct repo definition (as mentioned behind the link in your above first message) is:
```
   <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
 ```
... as mentioned: works for me.

**Comment by Prakash-Saravanan** [comment]
Thanks for quick reply.

The same worked for me using gradle until last week. These issues seem to be occurring from this week only.

Can you please share the issue link for gradle problem with sikulix POM?

**Comment by RaiMan** [comment]
https://bugs.launchpad.net/sikuli/+bug/1410072

**Comment by Prakash-Saravanan** [comment]
Thank you so much. For now I am able to resolve the issue by adding the following 

```
compile ('com.sikulix:sikulixapi:1.1.1-SNAPSHOT') {
        exclude module: '${sikulix.libs}'
        exclude module: 'jadb'
}
```
Expecting the next release :)
