### ISSUE TITLE
Region onChange/Observe fails when using class ImageFinder

### ISSUE THREAD

**Issue by HammySession** [RaiMan/SikuliX-2014#237]
When setting doing the following 
 ```
 import sikuli as sk
 def changed(event): print event.region
 sk.Settings.useImageFinder = True
 region_to_observe = sk.Screen()
 region_to_observe.onChange(changed)
 region_to_observe.observe(5)
```
no changes are detected even with moving items around on the screen, but if you change

```
sk.Settings.useImageFinder = False
region_to_observe.observe(5)
```

the changes are detected.

The root cause appears to hinge on ImageFinder. I know this is an experimental feature, but wanted to inform you of this issue.

**Comment by RaiMan** [comment]
Thanks.
... but the observe feature is not implemented in class ImageFinder (and will not be in 1.1.x).

This was some prework for version 2.
