### ISSUE TITLE
onChange perfomance decay

### ISSUE THREAD

**Issue by Vadiml1024** [RaiMan/SikuliX-2014#240]
I'm running siukilx 1.1.1 under ubuntu 14.04
And seeing performance decay of the attached code:

At the beginning of the run the code detects the images immedeatly upon
appearnce.
But at the end of 3 hours... It take 2 seconds to detect.

Any ideas or suggestions

```
#  winImage.WxH(): 42 x 18
#  lossImage.WxH(): 44 x 21
#  resultRgn: R[1149,563 87x240]@S(0)[0,0 1920x1080] E:Y, T:3,0

def resultChanged(evt):
    global winImage,lossImage
    global WINNING,LOSING,TIE
    
    r = evt.getRegion()
    WINNING = r.exists(winImage,0)
    LOSING = r.exists(lossImage,0)
    
    if WINNING or LOSING:
        evt.stopObserver()          
    return 

def validate():
    resultRgn.wait(validatingPattern, TIMEOUT+5)
    resultRgn.onChange(resultChanged)    
    resultRgn.observe(10)
```

**Comment by RaiMan** [comment]
Code compacted a little bit

**Comment by RaiMan** [comment]
Supposing, that resultRgn is a global, constant Region object, the reason for the slowdown seems not to be inside the shown functions.

An alternative solution without observe would be something like this:

```
def validate(reg, img1, img2, waitTime):
    isImg1 = False
    isImg2 = False
    end = time.time() + waitTime
    while time.time() < end:
        isImg1 = reg.exists(img1,0)
        isImg2 = reg.exists(img2,0)
        if isImg1 or isImg2:
            break
    return (isImg1, isImg2)

resultRgn.wait(validatingPattern, TIMEOUT+5)
(WINNING, LOOSING) = validate(resultRgn, winImage, lossImage, 10)
 ```
The function validate() could be used generally, to wait for 2 images in a region.

**Comment by Vadiml1024** [comment]
Thank you for the feedback...
I'll try this code....
