### ISSUE TITLE
Guide elements are shownd off target

### ISSUE THREAD

**Issue by Vadiml1024** [RaiMan/SikuliX-2014#242]
I'm trying  following code:

```from guide import *
logo = find("Logo.png")

rectangle(Region(logo).nearby(20))
#rectangle(Region(logo).nearby(20), offset=(-18,-7))

show(20)
```
For some reason the resulting rectangle is shown to the right and down 
of the target region as shown here: [http://imgur.com/mGMiOtk](http://imgur.com/mGMiOtk)

I need to use offset argument to position it back to correct place.
Any ideas what i'm doing wrong?

**Comment by RaiMan** [comment]
cannot reproduce this problem with version 1.1.1 final.
