### ISSUE TITLE
Pass variables via RESTful calls

### ISSUE THREAD

**Issue by briancerny** [RaiMan/SikuliX-2014#243]
It would be nice to add the ability to the experimental RunServer to pass variables to a SikuliX Python script via query string parameters. I've looked at the source code for the RunServer and it appears that this would be rather easy for one to implement. All that would need to be done is to parse the query string parameters and pass it for a different method of the script runner.

I need this for a current project I'm working on and have no problem contributing this code back to the project, especially since SikuliX is so good and useful.

**Comment by briancerny** [comment]
OK. Got everything checked out and built with the code changes. Only needed to modify the RunServer class. Need to do some testing and then I'll submit a pull request.

**Comment by RaiMan** [comment]
great. thanks.

**Comment by RaiMan** [comment]
enhancements merged
