### ISSUE TITLE
Image isn't found on full screen mode window

### ISSUE THREAD

**Issue by kenorb** [RaiMan/SikuliX-2014#261]
I've BlueStacks app (Android emulator) and this code works when the window is not in full-screen:

```
app = App("BlueStacks")
app.focus()
region = Region(App.focusedWindow())
region.click("JTi.png")
```

But the script fails to find the image, when the app is in full screen (in another workspace).

The error is as follow:

```
[log] App.focus: [28084:BlueStacks]
[error] script [ MyScript ] stopped with error in line 4
[error] FindFailed ( JTi.png: (80x89) seen at (1772, 922) with 1.00 in R[0,0 1920x1200]@S(0) E:Y, T:3.0 )
```

I'm using SikulixIDE 1.1.1 on macOS Sierra.

**Comment by RaiMan** [comment]
Full screen is  not supported, sorry.
