### ISSUE TITLE
[Downloads] page is empty at raiman.github.io

### ISSUE THREAD

**Issue by kenorb** [RaiMan/SikuliX-2014#262]
URL: https://raiman.github.io/SikuliX-2014/

When clicking on [Downloads], the page is blank. Is it expected behaviour?

Final URL: https://raiman.github.io/SikuliX-2014/downloads.html

**Comment by RaiMan** [comment]
Surely not intended ;-)
thanks

**Comment by RaiMan** [comment]
fixed
