### ISSUE TITLE
Alternatives to SikuliX

### ISSUE THREAD

**Issue by kenorb** [RaiMan/SikuliX-2014#263]
I'd like to know if there are any similar projects to SikuliX (especially which can work with Python). I like SikuliX, but I'd like to know if there are any similar projects, so I can compare them in terms of features. I'm aware of next version: [SikuliX2](https://github.com/RaiMan/SikuliX2) which is still in the development.

Do you know any? Thank you in advance.

**Comment by RaiMan** [comment]
There are some commercial products.
... but I do not know any other free projects. Only those, that wrap SikuliX somehow.

**Comment by tobimensch** [comment]
@kenorb 

I also want a solution like SikuliX that will work with python and/or other scripting languages.

In fact the only part of SikuliX I need is the GUI detection.

I would like to feed it with a screenshot and a get a tree of text/buttons/icons/tooltips/images with the position on the screen (x,y,w,h) in return.

Clicking can easily be done with xdotool and the like.

**Comment by kenorb** [comment]
Yep, it seems there is no good alternatives at the moment.

I'm going to close this issue in favor of the threads below.

So as for the follow-up, please check the following posts which have further tool recommendations:

- [Python GUI automation library for simulating user interaction in apps](https://softwarerecs.stackexchange.com/q/42664/3474)
- [GUI scipting for Linux](https://softwarerecs.stackexchange.com/q/22896/3474)
