### ISSUE TITLE
Getting “cannot load Java class org.sikuli.script.Keys” while trying to run cucumber test using sikulix

### ISSUE THREAD

**Issue by EugeneMarrow** [RaiMan/SikuliX-2014#271]
Hi.
I'm trying to set up testing environment using sikuli+jruby+cucumber. So I've installed latest JDK, Sikulix 1.1.1 , and latest JRuby, set up the cucumber test inspired by https://github.com/fozzie63/sikuli-jruby-cucumber and when i'm trying to run test i get the following exception:

```
sikulitest EugeneMarrow$ cucumber 
missing class or uppercase package name (`org.sikuli.script.Keys'), caused by (NameError) cannot load Java class org.sikuli.script.Keys (NameError)
```
I've tried to: 
- downgrade to JDK 7 and switched back to JDK8; 
- reinstall JRuby; 
- use Sikulix Nightly Builds 1.1.2;

Hope somebody could help me.
Regards, Eugene

**Comment by RaiMan** [comment]
Since in the sources of SikuliX do not contain any reference to a class 

> org.sikuli.script.Keys

the problem must be in your sources

Before stepping into more complex scenarios, just make a basic functional test.

**Comment by RaiMan** [comment]
expired
