### ISSUE TITLE
If image content is changed but not name, old image content is searched 

### ISSUE THREAD

**Issue by parkwart** [RaiMan/SikuliX-2014#272]
Using   1.1.2-Snapshot from Sonatype
    
How i find my images to work with Match Similarity is:

Match m;
Pattern p = new Pattern(locator);
m = screen.wait(p,30);

Pre conditions:
image a with name a.png
image b with name b.png

How to reproduce:
1. Search for "a.png"
2. Image found with contant if original a.png
3. Rename a.png to b.png and b.png to a.png
4. Search for "a.png" with content of b, because it has been renamed

Expected:
sikulix finds content of original b.png(file name is a.png now)

Actual:
it still searches for content of original a.png

**Comment by parkwart** [comment]
also found this https://bugs.launchpad.net/sikuli/+bug/1673013 for ide seems not to be fixed in sikulix

**Comment by RaiMan** [comment]
This is due to the internal image caching. (As long as you use SikuliX features to change image content, this is reflected)

In your case SikuliX is not aware of the rename, so you have to actively reset the cache:
Image.reset();
After that the used images are again loaded from the file.
