### ISSUE TITLE
Can not run on MacOS 10.12.5

### ISSUE THREAD

**Issue by DenisSch** [RaiMan/SikuliX-2014#274]
I am getting the following error when I try to run the SikuliS-1.1.1 after installation on MacOS 10.12.5:

> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/sikuli/ide/Sikulix : Unsupported major.minor version 51.0

**Comment by RaiMan** [comment]
Be sure to use the latest SikuliX 1.1.1 and have a valid Java 7 or Java 8 installation.
