### ISSUE TITLE
Java: ImagePath not available when running from Eclipse as runnable jar

### ISSUE THREAD

**Issue by tuyen** [RaiMan/SikuliX-2014#275]
I have downloaded the TestRunMaven project and import as maven project into eclipse, run the main class TestRun on eclipse => works!
I tried to export this project as runnable jar file (with 1st option in library handling) => run the jar with command: `java -jar sikuli3.jar`
=> result error:
`D:\Users\tuyennta\workspace\default\Sikuli-demo\run\sikili-image>java -jar sikuli3.jar`
`[debug] ImagePath: add: jar:file:/D:/Users/tuyennta/workspace/default/Sikuli-demo/run/sikili-image/sikuli3.jar!/ImagesAPI.sikuli`
`[debug] ImagePath: new BundlePath:/D:/Users/tuyennta/workspace/default/Sikuli-demo/run/sikili-image/`
`[error] Image: Image not valid, but TextSearch is switched off!`
`[debug] Region: handleImageMissing: test.png`
`[debug] Region: handleImageMissing: Response.ABORT: aborting`
`[error] RunTimeAPI: Wait: Abort: unknown`
`[error] RunTimeAPI: ImageMissing: test.png`
`[debug] RunTimeAPI: final cleanup`
`[debug] FileManager: deleteFileOrFolder:D:\Users\tuyennta\AppData\Local\Temp\Sikulix_1213072878`
Here is the structure of runnable jar:
![sikuli3](https://user-images.githubusercontent.com/12403480/28904889-2e36a098-7838-11e7-8bb5-b26dac8b05c5.PNG)
P/s: I also read the [document](http://sikulix-2014.readthedocs.io/en/latest/scripting.html#index-2) and followed step to create a general java project or maven project, both worked when run in eclipse and did not work when export to jar file.

**Comment by dmcgill50** [comment]
Are you able to find test.png in your runnable jar bundle? What's the path?

**Comment by RaiMan** [comment]
In this environment/usage one has to use a class based imagepath, which is still valid, when running as standalone jar.
