### ISSUE TITLE
Unable to install Sikulix 1.1.1. 

### ISSUE THREAD

**Issue by JoelJoy58** [RaiMan/SikuliX-2014#291]
This is where i am getting error.

[debug (11/27/17 7:23:28 PM)] FileManager: buildJar: adding: sikulixjython.jar
[error (11/27/17 7:23:42 PM)] FileManager: buildJar: java.io.EOFException: Unexpected end of ZLIB input stream
[debug (11/27/17 7:23:42 PM)] RunSetup: renaming sikulixtemp.jar to target jar: sikulix.jar
[debug (11/27/17 7:23:42 PM)] RunSetup: rename did not work --- trying copy
[debug (11/27/17 7:23:42 PM)] FileManager: deleteFileOrFolder:
C:\Users\10612159\Desktop\New folder\sikulixtemp.jar
[error (11/27/17 7:23:42 PM)] RunSetup: did not work
[error (11/27/17 7:23:42 PM)] RunSetup: 
[error (11/27/17 7:23:42 PM)] RunSetup: ... terminated abnormally :-(
[debug (11/27/17 7:23:42 PM)] RunSetup:

**Comment by RaiMan** [comment]
Delete everything related to SikuliX setup and start all over new.

**Comment by JoelJoy58** [comment]
That works  Thanks :)
