### ISSUE TITLE
failing to identify the image

### ISSUE THREAD

**Issue by kushalbn** [RaiMan/SikuliX-2014#297]
I am trying to identify this image:
![image 1](https://user-images.githubusercontent.com/35060746/34514093-863e8b8a-f091-11e7-9c90-0b2beb395017.PNG)
on the desktop which looks like this:
![desktop](https://user-images.githubusercontent.com/35060746/34514152-d0e4c05a-f091-11e7-9e16-38775206823a.PNG)

but, it is not recognizing it.
I have tried to capture image by zooming in, covering more backgroundarea in the image to be recognized, covering very less background area(white background), but none of them seem to be working.

Please Let me know if you have any solution.

**Comment by RaiMan** [comment]
capture as little background as possible!
... just the max rectangle inside the blue circle

**Comment by kushalbn** [comment]
well thanks for suggestion,
but there are times when greencircle with heart might not appear, so i need to verify if that heart inside green circle is present along with that blue circle...

**Comment by RaiMan** [comment]
Those situations are a bit tricky, but this is a possible solution:

after having found the base image as suggested, just check wether the heart is there in an appropriate region at the top right of the match:

```
match = exists(baseImage)
if match:
    regHeart = match.getTopRight().grow(100)
    if regHeart exists(heartImage):
       # do what is needed
    else:
       # do something else
```

**Comment by kushalbn** [comment]
ok thankyou..
