### ISSUE TITLE
Control throws FinFailed when action screen.click

### ISSUE THREAD

**Issue by nguyendinhthuan789** [RaiMan/SikuliX-2014#300]
Hi RaiMan,

Can you help me control using throws FinFailed when action screen.click (sikuliapi 1.1.1 sikuli core 1.2.0)  because i see if case failed this case always passed.
so I don't want using throw FindFailed in function, how can please help me. :(
thanks

<img width="342" alt="screenshot at jan 16 21-46-35" src="https://user-images.githubusercontent.com/24774362/34994844-5bdc086a-fb07-11e7-91cd-172d0b4961b2.png">

<img width="1195" alt="screenshot at jan 16 21-49-30" src="https://user-images.githubusercontent.com/24774362/34994856-63c9deda-fb07-11e7-90e4-517916874141.png">

**Comment by RaiMan** [comment]
the final image path is not correct!

> .../windows10//selectlanguage ...

BTW: sikuli core 1.2.0 has nothing to do with SikuliX.

**Comment by nguyendinhthuan789** [comment]
Thanks RaiMan
Can you look at in the case this FAILED (missing path image) the console is ERROR but results tree at the right bottom is PASSED
this is sikuli try catch(FindFailed) 
Thanks

**Comment by RaiMan** [comment]
If you are talking about unit testing, you have to use assert to control failed/passed of a test.

**Comment by nguyendinhthuan789** [comment]
Hi RaiMan
Thanks for your support
Yes, I'doing sikuli for testing Application on Desktop Windows, and using testNG FW assert, 
Currently I have using assert to control case PASSED or FAILED
I see if using throw Exception the case is FAILED but using FindFailed case PASSED

![screenshot_1](https://user-images.githubusercontent.com/24774362/35083713-04d705d6-fc53-11e7-8ac7-f76b0f41f66b.png)
![screenshot_2](https://user-images.githubusercontent.com/24774362/35083720-0cf28dee-fc53-11e7-9d7b-7177b0ebc461.png)

**Comment by RaiMan** [comment]
Since you catch the FindFailed without any action, the information is lost for the rest of your code.

Screenshots of code are not very helpful, since it is not possible to copy&paste for suggestions.
so only some meta-code:

```
try {
    click(...)
    return new Mainpage(sikulix)
} catch (...)
    return null
}
```

... and then in the test:

```
assert null != selectLanguage....
```

**Comment by nguyendinhthuan789** [comment]
Hi @RaiMan 
Thanks for your support
I think you were wrong for me.  I think when using catch (FindFailed ) if case false it will redirect to catch and this case is Failed just now.
Not to avoid to crash the app.

**public MainPage selectEnglish() {
        try {
            waitU.sleep(2500);
            String english = path_image_os + "/selectlanguage/english.png";   **// example this failed path**
            sikulix.click(english);
        } catch (FindFailed failed) {
              failed.printStackTrace();
        }
        return new MainPage(sikulix);
    }**
---------------
 **@Test(description = "select english language")
    public void setSelectLanguagePage() {
        Assert.assertTrue(verifyThePopup.verifyImageExists(selectLanguagePage.getImageEnglish()));
        selectLanguagePage.selectEnglish();
    }**

---------
**public boolean verifyImageExists(String images){

        boolean isValid = false;
        try {
            //Wait 10ms for image
            sikulix.waitVanish(images,10);
            if(sikulix.exists(images)!= null)
            {
                isValid = true;
            }
        }
        catch(Exception e){
        }
        return isValid;
    }**

Thanks

**Comment by RaiMan** [comment]
In the future please post questions like this on the launchpad page (larger community):
https://answers.launchpad.net/sikuli

Your solution looks odd to me.
... but I am glad you are happy.
