### ISSUE TITLE
Issue:The images are not getting identified when We execute the Sikulix script in different laptop

### ISSUE THREAD

**Issue by MuppuBala** [RaiMan/SikuliX-2014#307]
The images are not getting identified when We execute the Sikulix script in different laptop

Is there any possibility to adjust the pixel levels(height,Width, color) of image or display settings common for the Laptops we use.Any suggestion that SikuliX inbuilt methods can have a control on resolution?

**Comment by RaiMan** [comment]
Sorry, you have to live with that.
In doubt you have to have a different image set for each specific environment.
To avoid that, a base requirement is the same resolution on each system (the image must be there with the same width and height in pixels).
Another recommendation is, to concentrate the images on the key aspects, that make them findable, meaning to have as little background as possible towards the edges. This makes the search more robust against theme differences.
The rest is dealing with the match score.
Currently, there are no features in SikuliX, to adjust images in any way.
