### ISSUE TITLE
[Feature request] IDE - Autocomplete

### ISSUE THREAD

**Issue by tetreum** [RaiMan/SikuliX-2014#309]
Thanks for making SikuliX!

It would be really helpful to have autocomplete for `.sikuli` scripting as documentation is quite hard to read because of it's ui. 
https://imgur.com/a/yq5vy

For documentation UI, it may be more cool something like:
https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseDown.html

You immediately see a brief description + working example on how it's used and from which class does that method come.

**Comment by RaiMan** [comment]
If you want to have that, you have to script with a mature IDE like PyCharm, Eclipse PyDev, ...
For image management you can still use the SikuliX IDE in parallel.

I am sorry, I will not incorporate any new features into this more than 5 years old horrible;-) bunch of code, inherited from the original developers. It is hard enough to keep this stuff running with Java 9+

Hope you understand.
