### ISSUE TITLE
How would I silently install the latest stable package?

### ISSUE THREAD

**Issue by AnthonyMastrean** [RaiMan/SikuliX-2014#82]
I'm the maintainer of the [Chocolatey package](https://chocolatey.org/packages/sikuli) for Sikuli. I was just notified by a user that the 1.0-rc3 download link on launchpad is gone. I found that the sikuli project moved from sikuli-x to sikulix on LaunchPad, so that's ok.

I figured I'd update the package for SikuliX v1.0.1. I grabbed the latest package, the executable JAR and double-clicked to extract the script and ran that until I got into the installer UI. I'm curious about how to script that for a silent install, let's say Pack 1 (or any given Pack, Chocolatey does support passing parameters from the command line to the installer).

I don't know how that JAR works... does it use the system default program for JAR files? How do I do this silently? Would I do something like...

```text
> explorer.exe sikuli-setup.jar
```

If I can get that command script out, then I need to know if there are and how to pass parameters to pick a setup pack. I'm not sure where to start looking in the Java code for any options.

```text
> ./runSetup.cmd ???
```

Thanks for any help!

**Comment by RaiMan** [comment]
should be solved
