### ISSUE TITLE
Ubuntu - libVisionProxy.so: libopencv_core.so.2.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dhoer** [RaiMan/SikuliX-2014#85]
@RaiMan https://github.com/dhoer/chef-sikulix/issues/2
 
I see this has already been raised: https://answers.launchpad.net/sikuli/+question/252010
 
I would like to help if I could with this. Package managers scare me. If you are in the same boat, fpm might be worth a look: https://github.com/jordansissel/fpm.  It makes it easy to crank out packages, so maybe libVisionProxy could be packaged with this.

**Comment by dhoer** [comment]
I'm still getting the following issue for Ubuntu 14.04 below during setup.  The libs directory is created by sikulixsetup during export of tessdata.  I'm not compiling libVisionProxy.so or libJXGrabKey.so. I'm assuming native library is available.

Ubuntu 14.04 Setup
1. perform apt-get update
2. install open jdk 7
3. install packages wmctrl, libopencv-dev, and libtesseract-dev
4. download sikulixsetup
5. execute sikulixsetup 
6. install xvfb and start remote server as a init.d service with display :0

```
[log (1/4/15 9:51:37 PM)] ResourceLoader: check: Please wait! Trying to extract libs to jar parent folder:
/usr/local/sikulix/
[debug (1/4/15 9:51:37 PM)] ResourceLoader: extractLibs: from: /usr/local/sikulix/sikulixapi.jar
[debug (1/4/15 9:51:37 PM)] ResourceLoader: extractLibs: Found 0 Files in META-INF/libs/linux/libs64/
[debug (1/4/15 9:51:37 PM)] ResourceLoader: checkLibsDir: trying: /usr/local/sikulix/libs
[error (1/4/15 9:51:37 PM)] ResourceLoader: checkLibsDir: Not a valid libs dir for SikuliX (amd64): /usr/local/sikulix/libs
[error (1/4/15 9:51:37 PM)] ResourceLoader: check: Fatal Error 103: No valid native libraries folder available - giving up!
[error (1/4/15 9:51:37 PM)] Sikulix: ***** Terminating SikuliX Setup after a fatal error 103 *****
SikuliX is not useable!
```

```
vagrant@sikulix-ubuntu-1404:/usr/local/sikulix$ ls -al
total 99048
drwxrwxr-x  5 root root     4096 Jan  4 21:51 .
drwxr-xr-x 11 root root     4096 Jan  4 21:07 ..
drwxr-xr-x  2 root root     4096 Jan  4 21:51 Downloads
drwxr-xr-x  6 root root     4096 Jan  4 21:51 Lib
drwxr-xr-x  3 root root     4096 Jan  4 21:51 libs
-rw-r--r--  1 root root    19331 Jan  4 21:51 SikuliX-1.1.0-SetupLog.txt
-rw-r--r--  1 root root 25043426 Jan  4 21:51 sikulixapi.jar
-rwxr-xr-x  1 root root 76319549 Jan  4 21:51 sikulix.jar
-rw-r--r--  1 root root    10063 Jan  4 21:51 sikulixremoteserver.jar
```

```
vagrant@sikulix-ubuntu-1404:/usr/local/sikulix$ tree
.
├── Downloads
│   ├── 1.1.0-1.jar
│   ├── 1.1.0-2.jar
│   ├── 1.1.0-3.jar
│   ├── 1.1.0-6.jar
│   ├── jruby-complete-1.7.13.jar
│   ├── jython-standalone-2.7-b2.jar
│   ├── sikulixlibslux-1.1.0-20150102.002006-64.jar
│   ├── sikulixlibsmac-1.1.0-20150102.001759-64.jar
│   ├── sikulixlibswin-1.1.0-20150102.001345-64.jar
│   └── tesseract-ocr-3.02.eng.tar.gz
├── Lib
│   ├── HTMLTestRunner.py
│   ├── sikuli
│   │   ├── Env.py
│   │   ├── Finder.py
│   │   ├── __init__.py
│   │   ├── Region.py
│   │   ├── Screen.py
│   │   ├── SikuliImporter.py
│   │   └── Sikuli.py
│   ├── sikulix.rb
│   ├── xlrd
│   │   ├── biffh.py
│   │   ├── book.py
│   │   ├── compdoc.py
│   │   ├── formatting.py
│   │   ├── formula.py
│   │   ├── info.py
│   │   ├── __init__.py
│   │   ├── licences.py
│   │   ├── sheet.py
│   │   ├── timemachine.py
│   │   ├── xldate.py
│   │   └── xlsx.py
│   ├── xlutils
│   │   ├── copy.py
│   │   ├── display.py
│   │   ├── filter.py
│   │   ├── __init__.py
│   │   ├── license.txt
│   │   ├── margins.py
│   │   ├── save.py
│   │   ├── styles.py
│   │   ├── version.txt
│   │   └── view.py
│   ├── xlwt
│   │   ├── antlr.py
│   │   ├── BIFFRecords.py
│   │   ├── Bitmap.py
│   │   ├── Cell.py
│   │   ├── Column.py
│   │   ├── CompoundDoc.py
│   │   ├── excel-formula.g
│   │   ├── ExcelFormulaLexer.py
│   │   ├── ExcelFormulaParser.py
│   │   ├── ExcelFormula.py
│   │   ├── ExcelMagic.py
│   │   ├── Formatting.py
│   │   ├── __init__.py
│   │   ├── Row.py
│   │   ├── Style.py
│   │   ├── UnicodeUtils.py
│   │   ├── Utils.py
│   │   ├── Workbook.py
│   │   └── Worksheet.py
│   ├── XMLTestRunner1.py
│   └── XMLTestRunner2.py
├── libs
│   └── tessdata
│       ├── eng.cube.bigrams
│       ├── eng.cube.fold
│       ├── eng.cube.lm
│       ├── eng.cube.nn
│       ├── eng.cube.params
│       ├── eng.cube.size
│       ├── eng.cube.word-freq
│       ├── eng.tesseract_cube.nn
│       └── eng.traineddata
├── SikuliX-1.1.0-SetupLog.txt
├── sikulixapi.jar
├── sikulix.jar
└── sikulixremoteserver.jar
```

**Comment by RaiMan** [comment]
sorry for the late answer, but I wanted to try to fix this first.

with the setup jar from nightly today (2015-01-06) it should work now.

see my comment at
https://bugs.launchpad.net/sikuli/+bug/1407822

one caveat: I removed the remote server from setup. So just use a jar you already have.
I will provide a download option again later.

Do you need it as setup option?

**Comment by dhoer** [comment]
Results from (2015-01-06) build:

```
[error (1/6/15 6:01:03 PM)] ResourceLoader: check: No valid libs path available until now!
[log (1/6/15 6:01:03 PM)] ResourceLoader: check: Please wait! Trying to extract libs to jar parent folder:
/usr/local/sikulix/
[debug (1/6/15 6:01:03 PM)] ResourceLoader: extractLibs: from: /usr/local/sikulix/sikulixapi.jar
[debug (1/6/15 6:01:03 PM)] ResourceLoader: extractLibs: Found 1 Files in META-INF/libs/linux/libs64/
[debug (1/6/15 6:01:03 PM)] ResourceLoader: checkLibsDir: trying: /usr/local/sikulix/libs
[error (1/6/15 6:01:03 PM)] ResourceLoader: checkLibsDir: Not a valid libs dir for SikuliX (amd64): /usr/local/sikulix/libs
[error (1/6/15 6:01:03 PM)] ResourceLoader: check: Fatal Error 103: No valid native libraries folder available - giving up!
[error (1/6/15 6:01:03 PM)] Sikulix: ***** Terminating SikuliX Setup after a fatal error 103 *****
```
Please note, that I did update the previous comment with `RunSetup: null` error.  The library issue I originally reported was due to libopencv-dev package not installed when I thought it was.
 
I added -d 3 flag hoping the output would be more verbose, but that doesn't seem to make a difference. Is -d 3 flag on by default for silent install?

As for the remote server;  I could install that as a separate action if that is your future direction in 2.0.0.  Please let me how you see remote server and remote robot playing out in the future.  Will these two be combined?  

One more question about setup and remote server, do they require headless display to run?  For remote server service, I have xvfb with display :0 but I'm not sure that is needed for remote server.  Is that assumption correct?

Thanks in advance for your help.

**Comment by RaiMan** [comment]
--- Debug output
setup generally runs with debug level 3 (interactive and silent) and the most details are always in the setup log file.

--- new setup with inline build (2015-01-06+)
if you have provided a libs folder in the setup folder before running setup, the contained libs will be recognised and tested and finally bundled with the target artefact (sikulix.jar and/or sikulixapi.jar).
Details about what happened and was done is in the log file.

that you get this log
[debug (1/6/15 6:01:03 PM)] ResourceLoader: extractLibs: from: /usr/local/sikulix/sikulixapi.jar
[debug (1/6/15 6:01:03 PM)] ResourceLoader: extractLibs: Found 1 Files in META-INF/libs/linux/libs64/
means, that the setup did not work as it should.
To clarify: send me the setup log file to the mail found on https://github.com/RaiMan

**Comment by RaiMan** [comment]
--- the remote stuff
**remoterobot** 
(the former remoteserver) is simply a Java Robot implementation, that accepts capture requests, mouse and keyboard actions via a socket  based communication.
The client side is started with a RemoteScreen().
It only works in non-headless environments and is useable.
I will keep this as the "poor man's remote solution", since it works right out of the box.
I will somehow bring back the possibility to download it separately. 

**remoteserver** 
is a http server, that accepts REST requests currently with a small feature subset.
The client is in RESTClient.
It is a contribution and in a very early stage. I have moved it to version 2.
For SikuliX it is vital, to have such a server, that processes SikuliX requests, since with this SikuliX features can be used from "everywhere".
Only runs non-headless.

**VNC-Client**
This is integrated into version 1.1.0, principally available and should work.
It is also a contribution, poorly documented and has nearly no exception handling (simply crashes, if something is as it should not be).
Since it only needs access to a suitable VNC-server, headless or not does not matter.
This will be a major topic with version 2.

**headless / non-headless**
Since the current implementation of SikuliX is based on the Java Robot feature, it only works, if Java in the GraphicsEnvironment has a real monitor or thinks it has one.
So if you run on a system, that does not have a real monitor, you have to setup your system in a way, that Java thinks it has a monitor (e.g. using the respective X11 features or whatever).

**Comment by dhoer** [comment]
We mainly test in the cloud on AWS.  While SikuliX will work for windows by running it in the foreground via auto-login, linux doesn't seem to be a viable option without headless support.  If Ubuntu support is a distraction to completing 1.1.0 release, then I can drop it from the Chef cookbook.  Otherwise; I am more than happy to continue working out the issues.

I will drop support for remote server until 2.0.0 release.
