### ISSUE TITLE
Error opening data file tessdata/tessdata/eng.traineddata

### ISSUE THREAD

**Issue by jiangjinpeng1** [RaiMan/SikuliX-2014#87]
in java project 
i have set TESSDATA_PREFIX=D:\sikulix\libs
and i can find tessdata/eng.traineddata  in D:\sikulix\libs
but when i run the program ：

Error opening data file tessdata/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by RaiMan** [comment]
fixed in 1.1.0 final

**Comment by jiangjinpeng21** [comment]
thanks
