### ISSUE TITLE
VNC version 4 is not supported

### ISSUE THREAD

**Issue by manolkalinov** [RaiMan/SikuliX-2014#88]
When using VNCScreen, Real VNC Server returns version code "RFB 004.001". In the SikuliX code, the VNC version is handled in VNCClient>protocolHandshake().  Right now the method only handles the minor version of the returned code (Major version 3 is assumed).  So this case is not handled.  And since Real VNC is pretty popular, I believe the issue is important for this release.

The fix is trivial.  The VNCv4 docs state that the client can return code "RFB 003.008" and proceed as if it's dealing with version 3. I tried it and it works. This means that only the switch case needs to be updated.

Another note - Exception handling is a bit lacking in this code area.  It took me a lot of time (and RaiMan's help) to figure out what's failing.

I can volunteer to help out with the fix and the error handling around the VNC parts. This is a great functionality to have in 1.1.0.

**Comment by RaiMan** [comment]
...  I can volunteer to help out with the fix and the error handling around the VNC parts.

this would be really great.
The easiest way is to fork the repo and generate pull requests.

Thanks for feedback and contribution.

BTW: You say: I tried it and it works.
Could you do me a favour and list your environment and relevant settings.

**Comment by manolkalinov** [comment]
Great, I'll do that.

Environment info:

Remote Target VM: 
OS: Windows 7 x64
RealVNC Server 5.2.2 x64bit (password authentication is OFF)
selenium-server-standalone-2.39.0.jar running

Client VM - Windows 7 x64

As for my temp dirty workaround, what I've done is to just add another switch case:
```
...
version = Integer.parseInt(protocolVersion.substring(10, 11));
            switch (version){
                case 1://VNC version 4 returns "RFB 004.001", so the sikuli code will extract the '1'
                  //then just set the protocolVersion to version 3.8 and version 8, so the Server will know to downgrade the connection.
                  protocolVersion = "RFB 003.008"; version = 8;break;
                case 3:break;
                case 7:break;
...
```

Let me know if you need any more info.
