### ISSUE TITLE
Unattended installation PERMANENTLY deletes files/folders in the working directory on Windows

### ISSUE THREAD

**Issue by AnthonyMastrean** [RaiMan/SikuliX-2014#91]
I suspect that most Windows users download the setup JAR into their Downloads folder. If they then run an unattended install from the command line, all of the other files and folders will be permanently deleted  (as in, not put into the Recycle Bin).

I just lost a bunch of files that I was storing there while playing with the unattended installation options. Luckily, I have machine-wide backup occurring continuously.

Here's a procedure to recreate the problem. Requires an installed Java (so that the default program for executing a JAR is Java). This uses PowerShell and a temporary location with fake important files.

```powershell
New-Item sikulixbug -Type Directory

Push-Location sikulixbug

# create "fake" important files/folders
New-Item "important" -Type Directory
New-Item "important/important.txt" -Type File
New-Item "important.txt" -Type File

# the important files should exist
@("important", "important\important.txt", "important.txt") | %{ Test-Path $_ }

(New-Object System.Net.WebClient).DownloadFile("http://nightly.sikuli.de/sikulixsetup-1.1.0.jar", "$pwd\sikulixsetup-1.1.0.jar")

# invoke the unattended installation
Start-Process -Wait .\sikulixsetup-1.1.0.jar "options 1.1"

# now they don't!
@("important", "important\important.txt", "important.txt") | %{ Test-Path $_ }

Pop-Location
```

**Comment by RaiMan** [comment]
This is by intention (at least currently for version 1.1.0):
the folder containing the SikuliX stuff (<SikuliXfolder>) MUST be exclusive for SikuliX.
For unattended setup only the folder <SikuliXfolder>\Downloads (may contain pre-downloaded artefacts) and on Linux the folder libs is protected against this clean-up.
It is up to you to move the created stuff (mainly skulixapi.jar and/or sikulix.jar) to wherever you want afterwards.
BTW: the next nightly build will no longer export the native libs (folder libs) to the folder containing the sikulix artefact, but to the temp folder area. And the folder recreation is no longer bound to the setup time, but to the build version.

One more thing: there is another options option notest, that skips the final tests, which might be useful on headless systems.
