### ISSUE TITLE
Unable to build the Setup module -- sikulixlibsvision not found

### ISSUE THREAD

**Issue by dcominottim** [RaiMan/SikuliX-2014#92]
I am trying to build the whole project in order to experiment with a few customizations, but the following dependency from the Setup module

```
<dependency>
    <groupId>com.sikulix</groupId>
    <artifactId>sikulixlibsvision</artifactId>
    <version>${project.version}</version>
</dependency>
```

cannot be found in the repository from http://mvn.is.inf.uni-due.de. Can any advice be offered, please?

**Comment by dcominottim** [comment]
I am trying to build the whole project in order to experiment with a few customizations, but the following dependency from the Setup module

```
<dependency>
    <groupId>com.sikulix</groupId>
    <artifactId>sikulixlibsvision</artifactId>
    <version>${project.version}</version>
</dependency>
```

cannot be found in the repository from http://mvn.is.inf.uni-due.de. Can any advice be offered, please?

**Comment by Mscht** [comment]
I had the same problem two weeks ago. I think it is not requiered anymore. You can just delete this dependency. As i understand, the related sources are know included in this project. Am i right, RaiMan?

**Comment by dcominottim** [comment]
@Mscht thank you for the heads up. However, although I am now able to build the whole project with `mvn clean install`, when I try running the Setup process (using option/Pack 1) as described in

https://github.com/RaiMan/SikuliX-2014/wiki/How-to-produce-the-ready_to_use-jar-packages

I click "Yes" on every popup in order to use the locally compiled jars and still get some errors in the Setup log
```
[debug (1/28/15 9:37:34 PM)] RunTimeSETUP: addToClasspath: file:/E:/repo/git/bitbucket/cetusti/SikuliX-2014/Setup/target/Setup/sikulix.jar
[debug (1/28/15 9:37:34 PM)] RunSetup: Jython: Trying to run functional test: running script statements via SikuliScript
[debug (1/28/15 9:37:37 PM)] ScriptRunner: initScriptingSupport: enter
[error (1/28/15 9:37:37 PM)] JythonScriptRunner: init: could not find sikuli.py in E:/repo/git/bitbucket/cetusti/SikuliX-2014/Setup/target/Setup/sikulixsetup-1.1.0.jar
[debug (1/28/15 9:37:39 PM)] ScriptRunner: initScriptingSupport: added: jython
[debug (1/28/15 9:37:39 PM)] ScriptRunner: initScriptingSupport: warning: org.sikuli.scriptrunner.IScriptRunner: Provider org.sikuli.scriptrunner.JRubyScriptRunner could not be instantiated
[debug (1/28/15 9:37:39 PM)] ScriptRunner: initScriptingSupport: exit with defaultrunner: jython (py)
[debug (1/28/15 9:37:39 PM)] RunSetup: main: runScriptTest: error: null
```
Finally, when I try to run a script in the IDE, the IDE disappears for a second and then shows up again without having run the script, but it doesn't show any errors at all. If I start the IDE by means of `runsikulix.cmd`, I see one of the errors from the Setup log

`[error] JythonScriptRunner: init: could not find sikuli.py in C:/Users/Danilo/De
sktop/Sikulix/sikulix.jar`

but if I inspect `sikulix.jar`, I can see the `Sikuli.py` file inside the `Lib` folder. I am pretty lost here. Any advice about this? :-(

**Comment by RaiMan** [comment]
sorry for the inconvenience:
I am currently doing some major changes, so not everything might work.

If you need valid jars, you have to use the latest nightly build.

The project will be ready again when the next nightly build is available (a few days).
