### ISSUE TITLE
where is libtesseract.so.3?

### ISSUE THREAD

**Issue by Zoe1808** [RaiMan/SikuliX-2014#94]
when i use with linux system, there is an error: 
[error] RunTimeAPI: Problematic lib: /tmp/SikulixLibs_201501261622/libVisionProxy.so (...TEMP...)
[error] RunTimeAPI: libVisionProxy.so loaded, but it might be a problem with needed dependent libraries
ERROR: ...TEMP...: libtesseract.so.3: there is no file or directory.
 so where is libtesseract.so.3?
i can only find libVisionProxy.so and libJXGrabKey.so in sikulixlibs/linux/libs32(libs64)
Help...

**Comment by Zoe1808** [comment]
"For Linux there will be advices and scripts available to get the needed libraries ready."
where can i find the advices and scripts?

**Comment by RaiMan** [comment]
the information is on the home page of SikuliX:
http://www.sikulix.com/quickstart.html

You have to install Tesseract 3, since the dependent stuff (OpenCV, Tesseract, ...) has to be provided by you on Linux in a any case.

What Linux?

**Comment by Zoe1808** [comment]
Got it! Thanks!
