### ISSUE TITLE
runsikulix.cmd problem on 64 bit systems.

### ISSUE THREAD

**Issue by umgelurgel** [RaiMan/SikuliX-2014#97]
Running 64bit Windows 8.1 - both c:\Program Files\Java\jre7 and c:\Program Files (x86)\Java\jre7 exist, but only the latter contains the java.exe executable. The following check in the script finds and uses the first directory, that's missing the executable.

:CHECKJAVA
set PROGRAMS=%ProgramFiles%
if defined ProgramFiles(x86) set PROGRAMS32=%ProgramFiles(x86)%

IF not EXIST __"%PROGRAMS%\Java\jre7"__ goto JAVA6
set JAVA_HOME=%PROGRAMS%\Java\jre7
goto JAVA_OK

Changing the section of the script to the following should resolve the problem.

:CHECKJAVA
set PROGRAMS=%ProgramFiles%
if defined ProgramFiles(x86) set PROGRAMS32=%ProgramFiles(x86)%

IF not EXIST __"%PROGRAMS%\Java\jre7\bin\java.exe"__ goto JAVA6
set JAVA_HOME=%PROGRAMS%\Java\jre7
goto JAVA_OK

**Comment by RaiMan** [comment]
ok, thanks.
even though it is only some fall back, looking for java.exe is better.

The suggested solution in such unclear situations is to set JAVA_HOME before running SikuliX.
