### ISSUE TITLE
Advised Maven location is wrong

### ISSUE THREAD

**Issue by paul-hammant** [RaiMan/SikuliX-2014#98]
com-skiluix isn't found anywhere, let alone on oss.sonatype.org. Not there's a dash between com and skiluix.  groupid is missing too.

Can you correct the following on http://sikulix-2014.readthedocs.org/en/latest/faq/030-java-dev.html (and other places).

<repository> <!– OSSRH: com.sikulix –>
<id>com-sikulix</id>
<name>com-sikulix</name>
<url>https://oss.sonatype.org/content/groups/public</url>
<layout>default</layout>
<snapshots>
<enabled>true</enabled>
<updatePolicy>always</updatePolicy>
</snapshots>
</repository>

**Comment by RaiMan** [comment]
Though id might be anything (I could name it blabla ;-) I changed to com.sikuli to avoid any confusion.

relevant for finding sikulixapi.jar are only groupId and artifactId in the dependency settings.
