### ISSUE TITLE
Error installing on OS X 10.10.2

### ISSUE THREAD

**Issue by JanKnudsen** [RaiMan/SikuliX-2014#99]
After downloading, building and moving the bundle to Applications, I start the app and get the message: The bundled Jython 2.7b3 cannot be used on Java 6! Run setup again in this environment. Click OK to terminate now.

I'm running Java 8u31.

Any ideas what to do?

**Comment by JanKnudsen** [comment]
From:

https://launchpad.net/sikuli/sikulix/1.0.1/+download/sikuli-setup.jar <https://launchpad.net/sikuli/sikulix/1.0.1/+download/sikuli-setup.jar>

3.5 MB from 16.01.2015

/Jan

**Comment by RaiMan** [comment]
1.0.1 does not work on OSX 10.10.

try with the nightly build 1.1.0 from http://sikulix.com

**Comment by JanKnudsen** [comment]
Installed 1.1.0 from Nightly Build.

Installation went OK, copied bundle to Applications, started and got this:



I am running Java 8.

**Comment by RaiMan** [comment]
… started and got this:

what did you get?

**Comment by JanKnudsen** [comment]
Sorry, I answered by email so the image of the message got list. It says: 

"The bundled Jython 2.7b3 cannot be used on Java 6! Run setup again in this environment. Click OK to terminate now."

**Comment by RaiMan** [comment]
please send me the setup log to my mail at https://github.com/RaiMan

**Comment by RaiMan** [comment]
In a terminal session issue the command:
/usr/libexec/java_home -V

and post the output here.

**Comment by JanKnudsen** [comment]
Oh, oh :-(

I was running Java SE 6 which the message indicated. I have now upgraded to Java SE 8 and Sikuli works OK.

Thank you for your help :-)

**Comment by RaiMan** [comment]
no problem. have fun.
… and come back with whatever question.
